delete from public.cbq_cases where source='fets';
with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 1', 'Performance Management', 'Kadalundi Precision Components — variance analysis and a supplier offer', 'Kadalundi Precision Components manufactures the KP-7 valve assembly for the marine equipment industry and produces 40,000 units annually. The company operates a standard absorption costing system; the standard cost card is reproduced in Exhibit 1 and actual results for the year just ended in Exhibit 2.

All materials purchased during the year were used in production, and there was no opening or closing inventory of raw materials or finished goods. Variable overhead is absorbed on direct labour hours.

An external supplier has offered to supply the KP-7 at $76.00 per unit under a one-year contract. If the company ceased production, $240,000 of the annual fixed overhead — a dedicated supervisor''s salary and line insurance — would be avoided. The remainder is general plant overhead that would be reallocated across other product lines. The floor space released could be sublet for $90,000 a year, although no tenant has yet been identified.

The Controller has asked you to analyse the year''s variances and to advise on the offer.', '[{"label": "Exhibit 1 — Standard cost", "caption": "Per KP-7 valve assembly", "columns": ["Cost element", "Quantity", "Rate", "Standard cost"], "rows": [["Direct materials", "2.50 kg", "$12.00", "$30.00"], ["Direct labour", "0.80 hr", "$25.00", "$20.00"], ["Variable overhead", "0.80 hr", "$15.00", "$12.00"], ["Fixed overhead (allocated)", "0.80 hr", "$22.50", "$18.00"], ["Total standard cost", "", "", "$80.00"]]}, {"label": "Exhibit 2 — Actual results", "caption": "Year ended 31 March", "columns": ["Item", "Actual"], "rows": [["Units produced", "40,000"], ["Direct materials purchased and used", "104,000 kg"], ["Total direct materials cost", "$1,300,000"], ["Direct labour hours worked", "33,600 hr"], ["Total direct labour cost", "$865,200"], ["Variable overhead incurred", "$520,000"], ["Fixed overhead incurred", "$735,000"], ["Fixed overhead budgeted", "$720,000"]]}]'::jsonb, 'Hard', 'fets', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'num', 12, 'Calculate the <b>direct materials price variance</b> for the year. Enter the amount as a positive whole number and indicate its direction.', 'No dollar sign, no commas.', '{"direction": true}'::jsonb, '{"value": 52000, "direction": "U"}'::jsonb, 'Actual price = $1,300,000 ÷ 104,000 kg = $12.50. Price variance = 104,000 × ($12.50 − $12.00) = $52,000 unfavourable.'),
  (2, 'num', 12, 'Calculate the <b>direct materials quantity (usage) variance</b> for the year.', 'No dollar sign, no commas.', '{"direction": true}'::jsonb, '{"value": 48000, "direction": "U"}'::jsonb, 'Standard quantity = 40,000 × 2.5 kg = 100,000 kg. Usage variance = (104,000 − 100,000) × $12.00 = $48,000 unfavourable.'),
  (3, 'list', 16, 'Complete the following statement by selecting the appropriate option in each field.', NULL, '{"fields": [{"label": "The direct labour rate variance is", "options": ["$25,200 favourable", "$25,200 unfavourable", "$40,000 unfavourable", "$21,000 unfavourable"]}, {"label": "and the direct labour efficiency variance is", "options": ["$40,000 favourable", "$40,000 unfavourable", "$41,200 unfavourable", "$25,200 unfavourable"]}]}'::jsonb, '{"values": ["$25,200 unfavourable", "$40,000 unfavourable"]}'::jsonb, 'Actual rate = $865,200 ÷ 33,600 = $25.75. Rate variance = 33,600 × ($25.75 − $25.00) = $25,200 U. Standard hours = 40,000 × 0.8 = 32,000. Efficiency variance = (33,600 − 32,000) × $25.00 = $40,000 U.'),
  (4, 'num', 12, 'Calculate the <b>variable overhead efficiency variance</b> for the year.', 'Variable overhead is absorbed on direct labour hours.', '{"direction": true}'::jsonb, '{"value": 24000, "direction": "U"}'::jsonb, '(33,600 − 32,000) × $15.00 = $24,000 unfavourable. The same 1,600 excess hours drive both the labour efficiency and the variable overhead efficiency variance.'),
  (5, 'dnd', 20, 'Classify each item according to whether it is relevant to the decision to continue manufacturing the KP-7 or to buy it from the supplier. <b>All five items must be placed.</b>', NULL, '{"items": [{"id": "a", "text": "Direct materials of $30.00 per unit"}, {"id": "b", "text": "General plant overhead reallocated to other lines"}, {"id": "c", "text": "Avoidable supervisor salary and insurance of $240,000"}, {"id": "d", "text": "Sublease income of $90,000 forgone by continuing"}, {"id": "e", "text": "The unfavourable materials variances reported this year"}], "zones": {"rel": "Relevant to the decision", "irr": "Not relevant to the decision"}}'::jsonb, '{"placement": {"a": "rel", "b": "irr", "c": "rel", "d": "rel", "e": "irr"}}'::jsonb, 'Relevant costs differ between the alternatives. Incremental variable costs and avoidable fixed overhead both cease if production stops, and the forgone sublease is an opportunity cost of continuing. Reallocated general overhead is incurred either way, and this year''s variances are sunk.'),
  (6, 'num', 16, 'Calculate the <b>relevant cost per unit of manufacturing</b> the KP-7 internally.', 'Include the opportunity cost. Two decimal places.', '{"decimals": true}'::jsonb, '{"value": 70.25, "tolerance": 0.005}'::jsonb, 'Variable cost $62.00 + avoidable fixed overhead $240,000÷40,000 = $6.00 + forgone sublease $90,000÷40,000 = $2.25, giving $70.25. Against the supplier''s $76.00, manufacturing is cheaper by $5.75 per unit, or $230,000 a year.'),
  (7, 'multi', 12, 'Which of the following would cast doubt on a recommendation to continue manufacturing internally? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply", "options": ["The supplier''s price is fixed for one year only and may rise on renewal.", "No tenant has yet been identified for the released floor space.", "Dismantling the line would make a later reversal of the decision costly.", "The allocated fixed overhead of $18.00 per unit exceeds the avoidable amount.", "Direct labour worked 1,600 hours more than standard during the year."]}'::jsonb, '{"values": [0, 1]}'::jsonb, 'A price rise on renewal and an unsecured sublease would each erode the $230,000 advantage. Dismantling costs argue for continuing, not against it. The overhead allocation and the labour variance describe the current position rather than risks to the recommendation.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);
with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 1', 'Planning, Budgeting and Forecasting', 'Malabar Foods — March cash budget', 'Malabar Foods packs and distributes spice blends across south India. The Treasurer prepares a rolling three-month cash budget and is finalising the figures for March.

Sales are made entirely on credit. Historically 40% of a month''s sales are collected in the month of sale, 50% in the following month and 8% in the second following month; the remaining 2% proves uncollectible and is written off.

Purchases in any month equal 60% of the <em>following</em> month''s budgeted sales. Suppliers are paid 30% in the month of purchase and 70% in the month after.

Fixed cash operating expenses run at $220,000 a month and are paid as incurred. Depreciation of $45,000 a month is charged in the income statement but is not a cash flow. The cash balance at 1 March is $150,000, and the Board requires a minimum month-end balance of $100,000. Any shortfall is met by drawing on a revolving credit facility.

Actual and budgeted sales are set out in Exhibit 1.', '[{"label": "Exhibit 1 — Sales", "caption": "Actual to February, budgeted from March", "columns": ["Month", "Sales"], "rows": [["December (actual)", "$700,000"], ["January (actual)", "$800,000"], ["February (actual)", "$900,000"], ["March (budget)", "$1,050,000"], ["April (budget)", "$1,200,000"]]}, {"label": "Exhibit 2 — Cash policy", "caption": "Board-approved treasury parameters", "columns": ["Parameter", "Value"], "rows": [["Cash balance at 1 March", "$150,000"], ["Minimum month-end balance", "$100,000"], ["Fixed cash operating expenses per month", "$220,000"], ["Monthly depreciation charge", "$45,000"], ["Collection pattern", "40% / 50% / 8%, 2% written off"], ["Supplier payment pattern", "30% in month, 70% following month"]]}]'::jsonb, 'Medium', 'fets', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'num', 15, 'Calculate the <b>total cash collected from customers in March</b>.', 'Whole dollars, no commas.', '{}'::jsonb, '{"value": 934000}'::jsonb, '40% × $1,050,000 + 50% × $900,000 + 8% × $800,000 = $420,000 + $450,000 + $64,000 = $934,000.'),
  (2, 'num', 15, 'Calculate the <b>total cash paid to suppliers in March</b>.', 'March purchases are based on April''s budgeted sales.', '{}'::jsonb, '{"value": 657000}'::jsonb, 'March purchases = 60% × $1,200,000 = $720,000; February purchases = 60% × $1,050,000 = $630,000. Payments = 30% × $720,000 + 70% × $630,000 = $657,000.'),
  (3, 'num', 15, 'Calculate the <b>cash balance at 31 March</b>, before any drawing on the credit facility.', 'Remember which charges are not cash flows.', '{}'::jsonb, '{"value": 207000}'::jsonb, '$150,000 + $934,000 − $657,000 − $220,000 = $207,000. Depreciation is excluded — it is not a cash flow.'),
  (4, 'list', 14, 'Complete the following statement about the March position.', NULL, '{"fields": [{"label": "At 31 March the company", "options": ["will need to draw on the facility", "will not need to draw on the facility"]}, {"label": "and the balance exceeds the required minimum by", "options": ["$107,000", "$207,000", "$57,000", "$207,000 shortfall"]}]}'::jsonb, '{"values": ["will not need to draw on the facility", "$107,000"]}'::jsonb, 'The closing balance of $207,000 exceeds the $100,000 minimum by $107,000, so no drawing is required.'),
  (5, 'dnd', 14, 'Classify each schedule according to whether it forms part of the <b>operating budget</b> or the <b>financial budget</b>.', NULL, '{"items": [{"id": "a", "text": "Sales budget"}, {"id": "b", "text": "Cash budget"}, {"id": "c", "text": "Direct materials purchases budget"}, {"id": "d", "text": "Capital expenditure budget"}, {"id": "e", "text": "Budgeted income statement"}, {"id": "f", "text": "Budgeted balance sheet"}], "zones": {"op": "Operating budget", "fin": "Financial budget"}}'::jsonb, '{"placement": {"a": "op", "b": "fin", "c": "op", "d": "fin", "e": "op", "f": "fin"}}'::jsonb, 'The operating budget builds to the budgeted income statement through sales, production, materials, labour and overhead. The financial budget covers cash, capital spending and the budgeted balance sheet.'),
  (6, 'mcq', 15, 'If collections were to slow to 30% in the month of sale, 50% in the following month and 18% in the second following month, with bad debts unchanged at 2%, what would the 31 March cash balance become?', NULL, '{"options": ["$182,000", "$207,000", "$157,000", "$232,000"]}'::jsonb, '{"value": "A"}'::jsonb, 'Collections fall to 30% × $1,050,000 + 50% × $900,000 + 18% × $800,000 = $909,000, a reduction of $25,000. The closing balance falls from $207,000 to $182,000 — still above the minimum, but the margin narrows sharply.'),
  (7, 'multi', 12, 'Which of the following are characteristics of <b>participative</b> budgeting? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply", "options": ["Targets are set by the managers who will be held accountable for them.", "It tends to improve motivation and acceptance of the budget.", "It creates a risk of budgetary slack.", "It is normally faster to prepare than an imposed budget.", "It removes the need for senior management review."]}'::jsonb, '{"values": [0, 1, 2]}'::jsonb, 'Participative budgeting involves the accountable managers in setting targets, which improves buy-in but invites slack. It is slower than an imposed budget, not faster, and senior review remains essential precisely because of the slack risk.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);
with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 1', 'Cost Management', 'Beypore Marine Fabricators — plantwide rate versus activity-based costing', 'Beypore Marine Fabricators builds two products: a Standard hull, produced in long runs, and a Custom hull built to order in small batches. Annual volumes are 8,000 Standard and 2,000 Custom.

Manufacturing overhead of $1,200,000 a year is presently absorbed using a single plantwide rate based on direct labour hours. The Standard hull requires 0.5 direct labour hours per unit and the Custom hull 2.0 hours.

Competitors have recently undercut Beypore''s price on the Standard hull, while the company continues to win Custom work comfortably on price. The Managing Director suspects the costing system is distorting the picture and has asked for an activity-based analysis. The Cost Accountant has identified three activity cost pools and their drivers, set out in Exhibit 2.', '[{"label": "Exhibit 1 — Volumes and labour", "caption": "Annual", "columns": ["Product", "Units", "Direct labour hours per unit", "Total direct labour hours"], "rows": [["Standard hull", "8,000", "0.5", "4,000"], ["Custom hull", "2,000", "2.0", "4,000"], ["Total", "10,000", "", "8,000"]]}, {"label": "Exhibit 2 — Activity cost pools", "caption": "Total overhead $1,200,000", "columns": ["Activity pool", "Pool cost", "Cost driver", "Standard hull", "Custom hull"], "rows": [["Machine setups", "$360,000", "setups", "40", "160"], ["Machining", "$600,000", "machine hours", "20,000", "10,000"], ["Inspection", "$240,000", "inspections", "200", "600"]]}]'::jsonb, 'Medium', 'fets', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'num', 13, 'Calculate the <b>plantwide overhead rate per direct labour hour</b>.', 'Two decimal places.', '{"decimals": true}'::jsonb, '{"value": 150.0, "tolerance": 0.005}'::jsonb, '$1,200,000 ÷ 8,000 direct labour hours = $150.00 per hour.'),
  (2, 'num', 13, 'Under the <b>plantwide rate</b>, calculate the overhead absorbed per <b>Standard</b> hull.', 'Two decimal places.', '{"decimals": true}'::jsonb, '{"value": 75.0, "tolerance": 0.005}'::jsonb, '0.5 hours × $150.00 = $75.00 per Standard hull.'),
  (3, 'num', 16, 'Under <b>activity-based costing</b>, calculate the overhead assigned per <b>Custom</b> hull.', 'Two decimal places. Work each pool''s driver rate first.', '{"decimals": true}'::jsonb, '{"value": 334.0, "tolerance": 0.01}'::jsonb, 'Setups $360,000 ÷ 200 = $1,800 each; 160 × $1,800 ÷ 2,000 = $144.00. Machining $600,000 ÷ 30,000 = $20.00 per hour; 10,000 × $20 ÷ 2,000 = $100.00. Inspection $240,000 ÷ 800 = $300 each; 600 × $300 ÷ 2,000 = $90.00. Total $334.00 per Custom hull.'),
  (4, 'num', 16, 'By how much per unit does the plantwide rate <b>undercost</b> the Custom hull?', 'Two decimal places.', '{"decimals": true}'::jsonb, '{"value": 34.0, "tolerance": 0.01}'::jsonb, 'ABC assigns $334.00 against the plantwide $300.00, so the Custom hull is undercosted by $34.00 per unit. The Standard hull is correspondingly overcosted by $8.50.'),
  (5, 'dnd', 14, 'Match each activity cost pool to the driver that best reflects what causes its cost.', NULL, '{"items": [{"id": "a", "text": "Machine setup costs"}, {"id": "b", "text": "Machine power and maintenance"}, {"id": "c", "text": "Quality inspection"}, {"id": "d", "text": "Factory building rent"}], "zones": {"batch": "Batch-level driver", "unit": "Unit-level driver", "fac": "Facility-level — no meaningful driver"}}'::jsonb, '{"placement": {"a": "batch", "b": "unit", "c": "batch", "d": "fac"}}'::jsonb, 'Setups and inspections are incurred per batch regardless of batch size. Machine power varies with machine hours, a unit-level driver. Building rent supports the plant as a whole and is arbitrarily allocated under any system.'),
  (6, 'multi', 16, 'Why does activity-based costing produce a materially different answer here? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply", "options": ["The Custom hull consumes batch-level activities out of all proportion to its labour hours.", "The plantwide rate assumes overhead is driven solely by direct labour hours.", "Activity-based costing assigns more total overhead than the plantwide method.", "The Standard hull''s high volume absorbs overhead it does not cause.", "Direct labour is the largest single element of the Custom hull''s cost."]}'::jsonb, '{"values": [0, 1, 3]}'::jsonb, 'ABC redistributes the same $1,200,000 — it never assigns more in total, which rules out the third option. The distortion arises because the low-volume Custom hull consumes setups and inspections far out of proportion to its labour hours, while the high-volume Standard hull absorbs overhead it does not cause.'),
  (7, 'mcq', 12, 'What does the analysis suggest about Beypore''s pricing?', NULL, '{"options": ["The Standard hull may be priced above the level its true cost requires, and the Custom hull below it.", "Both products are priced too low and a general increase is warranted.", "The Custom hull should be discontinued because it is unprofitable.", "Pricing should not change, since total overhead recovered is identical under both methods."]}'::jsonb, '{"value": "A"}'::jsonb, 'Overcosting the Standard hull inflates its price and explains why competitors undercut it; undercosting the Custom hull explains why Beypore wins that work easily. Discontinuation cannot be judged without contribution data, and identical total recovery says nothing about whether individual prices are right.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);
with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 2', 'Financial Statement Analysis', 'Ernakulam Ceramics — ratio analysis and return on equity', 'Ernakulam Ceramics manufactures sanitaryware for the domestic construction market. The Board has asked for an analysis of the year''s results ahead of a refinancing discussion with the company''s bankers.

The summarised income statement is in Exhibit 1 and the relevant balance sheet figures, with both opening and closing positions, in Exhibit 2. Use a 365-day year and average balances wherever an average is appropriate.

The bank has indicated that it monitors two things closely: the company''s ability to meet short-term obligations, and the length of time cash is tied up in the operating cycle. Management believes the return on equity is respectable but has not decomposed it to understand what is actually driving the figure.

All sales are on credit and all purchases are on credit terms with suppliers.', '[{"label": "Exhibit 1 — Income statement", "caption": "Year ended 31 March", "columns": ["Item", "Amount"], "rows": [["Revenue", "$5,000,000"], ["Cost of goods sold", "$3,000,000"], ["Gross profit", "$2,000,000"], ["Operating expenses", "$1,200,000"], ["Operating income", "$800,000"], ["Interest expense", "$100,000"], ["Income before tax", "$700,000"], ["Income tax at 30%", "$210,000"], ["Net income", "$490,000"]]}, {"label": "Exhibit 2 — Balance sheet extracts", "caption": "Opening and closing balances", "columns": ["Item", "1 April (opening)", "31 March (closing)"], "rows": [["Accounts receivable", "$380,000", "$420,000"], ["Inventory", "$550,000", "$650,000"], ["Accounts payable", "$280,000", "$320,000"], ["Total current assets", "—", "$1,400,000"], ["Total current liabilities", "—", "$700,000"], ["Total assets", "$3,800,000", "$4,200,000"], ["Shareholders'' equity", "$1,900,000", "$2,100,000"]]}]'::jsonb, 'Medium', 'fets', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'num', 12, 'Calculate the <b>current ratio</b> at 31 March.', 'Two decimal places.', '{"decimals": true}'::jsonb, '{"value": 2.0, "tolerance": 0.005}'::jsonb, '$1,400,000 ÷ $700,000 = 2.00.'),
  (2, 'num', 14, 'Calculate <b>days sales outstanding</b>, using average receivables.', 'One decimal place. 365-day year.', '{"decimals": true}'::jsonb, '{"value": 29.2, "tolerance": 0.06}'::jsonb, 'Average receivables = $400,000. Receivables turnover = $5,000,000 ÷ $400,000 = 12.50. DSO = 365 ÷ 12.50 = 29.2 days.'),
  (3, 'num', 16, 'Calculate the <b>cash conversion cycle</b> in days.', 'One decimal place. Inventory and payables turn on cost of goods sold.', '{"decimals": true}'::jsonb, '{"value": 65.7, "tolerance": 0.11}'::jsonb, 'Days inventory 73.0 + days sales outstanding 29.2 − days payables 36.5 = 65.7 days. Cash is tied up for roughly two months of every operating cycle.'),
  (4, 'list', 16, 'Complete the DuPont decomposition of return on equity, using average balances.', NULL, '{"fields": [{"label": "Net profit margin is", "options": ["9.8%", "16.0%", "9.0%", "14.0%"]}, {"label": "total asset turnover is", "options": ["1.25", "1.19", "2.50", "0.80"]}, {"label": "and the equity multiplier is", "options": ["2.00", "1.90", "2.10", "0.50"]}]}'::jsonb, '{"values": ["9.8%", "1.25", "2.00"]}'::jsonb, 'Margin $490,000 ÷ $5,000,000 = 9.8%. Asset turnover $5,000,000 ÷ $4,000,000 = 1.25. Equity multiplier $4,000,000 ÷ $2,000,000 = 2.00.'),
  (5, 'num', 12, 'Calculate <b>return on equity</b> as a percentage, using average equity.', 'One decimal place. Enter the number only, without a percent sign.', '{"decimals": true}'::jsonb, '{"value": 24.5, "tolerance": 0.06}'::jsonb, '$490,000 ÷ $2,000,000 = 24.5%, which is also 9.8% × 1.25 × 2.00. Half the return is coming from leverage, not from operations.'),
  (6, 'multi', 16, 'Which of the following would <b>shorten</b> the cash conversion cycle? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply", "options": ["Negotiating longer payment terms with suppliers.", "Offering customers an early settlement discount.", "Increasing inventory to improve product availability.", "Tightening credit approval for new customers.", "Refinancing short-term borrowing with a long-term loan."]}'::jsonb, '{"values": [0, 1, 3]}'::jsonb, 'Longer supplier terms raise days payable, which is subtracted. Early settlement discounts and tighter credit both reduce days sales outstanding. Holding more inventory lengthens the cycle, and refinancing changes the funding of working capital without changing the cycle itself.'),
  (7, 'dnd', 14, 'Classify each ratio by the category it belongs to.', NULL, '{"items": [{"id": "a", "text": "Current ratio"}, {"id": "b", "text": "Inventory turnover"}, {"id": "c", "text": "Equity multiplier"}, {"id": "d", "text": "Return on equity"}, {"id": "e", "text": "Times interest earned"}], "zones": {"liq": "Liquidity", "act": "Activity", "lev": "Leverage", "prof": "Profitability"}}'::jsonb, '{"placement": {"a": "liq", "b": "act", "c": "lev", "d": "prof", "e": "lev"}}'::jsonb, 'Liquidity ratios measure short-term solvency; activity ratios measure how hard assets work; leverage ratios measure the use and burden of debt, which covers both the equity multiplier and interest cover; profitability ratios measure return.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);
with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 2', 'Corporate Finance', 'Kochi Marine Services — cost of capital for a new division', 'Kochi Marine Services operates port logistics terminals and is evaluating entry into offshore survey work, a materially riskier business than its existing operations.

The company''s capital structure and market data are set out in Exhibit 1. Management intends to fund the new division at the same debt-to-equity proportions as the group and treats the current structure as its long-run target.

The Finance Director has proposed appraising the offshore survey project at the group''s weighted average cost of capital. The Chief Executive is uneasy, noting that quoted companies operating purely in offshore survey have equity betas averaging 1.6 against the group''s 1.2.

The corporate tax rate is 30%. Assume debt is issued at par and that the capital asset pricing model holds.', '[{"label": "Exhibit 1 — Capital structure and market data", "caption": "At the valuation date", "columns": ["Item", "Value"], "rows": [["Market value of debt", "$10,000,000"], ["Pre-tax cost of debt", "8.0%"], ["Ordinary shares in issue", "3,000,000"], ["Market price per share", "$10.00"], ["Corporate tax rate", "30%"], ["Risk-free rate", "4.0%"], ["Expected market return", "11.0%"], ["Group equity beta", "1.20"], ["Pure-play equity beta, offshore survey", "1.60"]]}]'::jsonb, 'Hard', 'fets', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'num', 12, 'Calculate the <b>after-tax cost of debt</b> as a percentage.', 'One decimal place. Enter the number only.', '{"decimals": true}'::jsonb, '{"value": 5.6, "tolerance": 0.06}'::jsonb, '8.0% × (1 − 0.30) = 5.6%. Interest is tax-deductible, so the cost to the company is the after-tax figure.'),
  (2, 'num', 14, 'Calculate the <b>group cost of equity</b> using the capital asset pricing model.', 'One decimal place. Enter the number only.', '{"decimals": true}'::jsonb, '{"value": 12.4, "tolerance": 0.06}'::jsonb, '4.0% + 1.20 × (11.0% − 4.0%) = 4.0% + 8.4% = 12.4%.'),
  (3, 'num', 16, 'Calculate the <b>group weighted average cost of capital</b> using market value weights.', 'One decimal place. Enter the number only.', '{"decimals": true}'::jsonb, '{"value": 10.7, "tolerance": 0.06}'::jsonb, 'Equity is 3,000,000 × $10.00 = $30,000,000, so weights are 25% debt and 75% equity. WACC = 25% × 5.6% + 75% × 12.4% = 10.7%.'),
  (4, 'num', 16, 'Calculate the <b>project-specific discount rate</b> for the offshore survey division, using the pure-play beta and the same capital structure.', 'One decimal place. Enter the number only.', '{"decimals": true}'::jsonb, '{"value": 12.8, "tolerance": 0.06}'::jsonb, 'Project cost of equity = 4.0% + 1.60 × 7.0% = 15.2%. Project rate = 25% × 5.6% + 75% × 15.2% = 12.8%, some 2.1 percentage points above the group figure.'),
  (5, 'list', 14, 'Complete the following statement about the Finance Director''s proposal.', NULL, '{"fields": [{"label": "Appraising the offshore project at the group WACC would tend to", "options": ["accept projects that destroy value", "reject projects that create value", "have no systematic effect"]}, {"label": "because the group rate is", "options": ["below the project''s risk-adjusted rate", "above the project''s risk-adjusted rate", "equal to the project''s risk-adjusted rate"]}]}'::jsonb, '{"values": ["accept projects that destroy value", "below the project''s risk-adjusted rate"]}'::jsonb, 'The group rate of 10.7% is below the 12.8% the project''s risk warrants. Discounting risky cash flows too lightly overstates net present value and leads to accepting projects that do not compensate for their risk.'),
  (6, 'multi', 16, 'Why are <b>market value</b> weights preferred to book value weights in a WACC calculation? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply", "options": ["Market values reflect what investors would require to supply capital today.", "Book equity is a historical figure and can differ greatly from market capitalisation.", "Market weights are more stable over time than book weights.", "The cost of each component is itself an expected market return."]}'::jsonb, '{"values": [0, 1, 3]}'::jsonb, 'WACC is a forward-looking opportunity cost, so both the weights and the component costs should be expressed in market terms. Market weights are in fact less stable than book weights, not more — that is a cost of the method, not a reason for it.'),
  (7, 'dnd', 12, 'Classify each source of risk according to whether it is systematic or unsystematic.', NULL, '{"items": [{"id": "a", "text": "A rise in the general level of interest rates"}, {"id": "b", "text": "Loss of the company''s largest single customer"}, {"id": "c", "text": "A national recession reducing port volumes"}, {"id": "d", "text": "A fire at one of the company''s terminals"}], "zones": {"sys": "Systematic risk", "unsys": "Unsystematic risk"}}'::jsonb, '{"placement": {"a": "sys", "b": "unsys", "c": "sys", "d": "unsys"}}'::jsonb, 'Systematic risk affects the whole market and cannot be diversified away — it is what beta measures and what investors are compensated for. Customer loss and fire damage are company-specific and diversifiable, so they carry no risk premium.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);
with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 2', 'Decision Analysis', 'Alappuzha Coir Exports — cost-volume-profit and an export order', 'Alappuzha Coir Exports manufactures woven coir matting. Its single product sells for $50.00 a unit with variable costs of $30.00, and annual fixed costs are $1,200,000. Practical capacity is 100,000 units a year and the company currently sells 80,000.

A European distributor has approached the company with a one-off order for 15,000 units at $38.00 each. The order would carry additional shipping and export documentation costs of $2.00 a unit; all other variable costs would be unchanged, and no additional fixed costs would be incurred. The distributor sells into markets Alappuzha does not currently serve, and the goods would carry the distributor''s own branding.

The Sales Director opposes the order on the grounds that $38.00 is below the full absorption cost of $45.00 a unit. The Managing Director has asked for a relevant-cost analysis before the Board meets.', '[{"label": "Exhibit 1 — Cost and volume data", "caption": "Current year", "columns": ["Item", "Value"], "rows": [["Selling price per unit", "$50.00"], ["Variable cost per unit", "$30.00"], ["Contribution margin per unit", "$20.00"], ["Annual fixed costs", "$1,200,000"], ["Practical capacity (units)", "100,000"], ["Current sales volume (units)", "80,000"], ["Full absorption cost per unit at current volume", "$45.00"]]}, {"label": "Exhibit 2 — Proposed export order", "caption": "One-off, non-recurring", "columns": ["Item", "Value"], "rows": [["Order quantity (units)", "15,000"], ["Price offered per unit", "$38.00"], ["Additional shipping and documentation per unit", "$2.00"], ["Additional fixed costs", "Nil"], ["Branding", "Distributor''s own"]]}]'::jsonb, 'Medium', 'fets', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'num', 13, 'Calculate the <b>breakeven volume in units</b>.', 'Whole units, no commas.', '{}'::jsonb, '{"value": 60000}'::jsonb, 'Contribution margin = $50.00 − $30.00 = $20.00. Breakeven = $1,200,000 ÷ $20.00 = 60,000 units.'),
  (2, 'num', 13, 'Calculate the volume in units required to earn an operating income of <b>$400,000</b>.', 'Whole units, no commas.', '{}'::jsonb, '{"value": 80000}'::jsonb, '($1,200,000 + $400,000) ÷ $20.00 = 80,000 units — which is exactly the current volume.'),
  (3, 'num', 13, 'Calculate the <b>margin of safety</b> at the current volume, as a percentage of sales.', 'One decimal place. Enter the number only, without a percent sign.', '{"decimals": true}'::jsonb, '{"value": 25.0, "tolerance": 0.06}'::jsonb, '(80,000 − 60,000) ÷ 80,000 = 25.0%. Volume could fall by a quarter before the company makes a loss.'),
  (4, 'num', 13, 'Calculate the <b>degree of operating leverage</b> at the current volume.', 'Two decimal places.', '{"decimals": true}'::jsonb, '{"value": 4.0, "tolerance": 0.01}'::jsonb, 'Total contribution $1,600,000 ÷ operating income $400,000 = 4.00. A 10% change in sales moves operating income by 40%.'),
  (5, 'num', 16, 'Calculate the <b>change in annual operating income</b> if the export order is accepted. Enter the amount as a positive whole number.', 'No dollar sign, no commas. Consider only relevant costs.', '{"direction": false}'::jsonb, '{"value": 90000}'::jsonb, 'Relevant cost per unit = $30.00 + $2.00 = $32.00. Contribution = $38.00 − $32.00 = $6.00 per unit × 15,000 = $90,000 increase. Fixed costs are unchanged, so the $45.00 absorption cost the Sales Director cites is not relevant to this decision.'),
  (6, 'multi', 16, 'Which of the following are legitimate reasons to <b>hesitate</b> over accepting the order? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply", "options": ["Existing customers may learn of the lower price and demand similar terms.", "Accepting sets a reference point for the distributor''s future orders.", "The price of $38.00 is below the full absorption cost of $45.00.", "The order would consume 15,000 units of the 20,000 units of spare capacity.", "The contribution per unit on the order is lower than on normal sales."]}'::jsonb, '{"values": [0, 1, 3]}'::jsonb, 'Price erosion among existing customers and anchoring the distributor''s expectations are real commercial risks, and consuming three-quarters of the spare capacity constrains any better opportunity that arrives later. Comparison with absorption cost is precisely the error the Sales Director made, and a lower contribution per unit is irrelevant so long as it is positive and capacity is idle.'),
  (7, 'mcq', 16, 'Suppose the distributor instead ordered 25,000 units on the same terms. What would the change in operating income be?', NULL, '{"options": ["$50,000 increase", "$150,000 increase", "$50,000 decrease", "No change, because capacity is exceeded"]}'::jsonb, '{"value": "A"}'::jsonb, 'Only 20,000 units of spare capacity exist, so 5,000 units of normal sales would be displaced. Gain = 25,000 × $6.00 = $150,000; loss = 5,000 × $20.00 = $100,000. Net $50,000 increase — still positive, but the opportunity cost of displaced sales has consumed two-thirds of the benefit.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);