with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 2', 'Risk Management', 'Munnar Tea Estates — euro receivable and hedge selection', 'Munnar Tea Estates exports orthodox black tea to a German distributor and has a firm euro-denominated receivable due in 90 days (Exhibit 1). The Treasurer is evaluating three hedges: a forward sale of euros, a euro put option, and a money-market hedge. The company''s home currency is the US dollar for reporting of this export contract.

Market quotes and interest rates are in Exhibit 2. After the hedges are analysed, the Board also wants a view on whether the exposure is transaction, translation, or economic, and which instruments leave upside if the euro strengthens.', '[{"label": "Exhibit 1 — Exposure","caption": "Export contract","columns": ["Item","Detail"],"rows": [["Receivable","EUR 400,000"],["Due in","90 days"],["Nature","Firm sale already shipped; invoice outstanding"],["Home currency for this analysis","US dollar"]]},{"label": "Exhibit 2 — Market data","caption": "Quotes at hedge inception; year basis 360 days","columns": ["Instrument / rate","Quote"],"rows": [["Spot rate ($/EUR)","1.120"],["90-day forward rate ($/EUR)","1.100"],["Euro put option strike ($/EUR)","1.105"],["Euro put premium ($ per EUR)","0.015"],["EUR 90-day interest rate (annualised)","4.0%"],["USD 90-day interest rate (annualised)","6.0%"],["Spot rate at maturity ($/EUR) — for ex-post evaluation","1.080"]]}]'::jsonb, 'Hard', 'fets_v2', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'mcq', 12, 'The EUR 400,000 invoice primarily creates which type of foreign-exchange exposure?', NULL, '{"options": ["Transaction exposure","Translation (accounting) exposure","Economic (operating) exposure only","No exposure, because the sale is already shipped"]}'::jsonb, '{"value": "A"}'::jsonb, 'A firm foreign-currency receivable whose settlement amount in home currency is not yet fixed is classic transaction exposure. Translation affects consolidated book values of foreign operations; economic exposure is the longer-term effect on competitive position.'),
  (2, 'num', 14, 'If the receivable is sold forward, calculate the <b>guaranteed dollar proceeds</b> at maturity.', 'Whole dollars, no commas.', '{}'::jsonb, '{"value": 440000}'::jsonb, 'EUR 400,000 x 1.100 = $440,000 locked in by the forward contract.'),
  (3, 'num', 16, 'Using the maturity spot of 1.080, calculate the <b>net dollar proceeds under the put option</b> (after premium). Premium is paid at inception; ignore time value of money on the premium for this task.', 'Whole dollars. Decide whether the option is exercised.', '{}'::jsonb, '{"value": 436000}'::jsonb, 'Spot 1.080 < strike 1.105, so exercise: EUR 400,000 x 1.105 = $442,000. Premium = 400,000 x 0.015 = $6,000. Net proceeds = $442,000 - $6,000 = $436,000.'),
  (4, 'num', 16, 'Calculate the <b>dollar proceeds today</b> from implementing the money-market hedge (borrow euros, convert at spot). Round to the nearest whole dollar.', '90/360 year fraction. Borrow the present value of EUR 400,000.', '{}'::jsonb, '{"value": 443564}'::jsonb, 'PV of receivable = 400,000 / (1 + 0.04 x 90/360) = 400,000 / 1.01 = 396,039.60396. Convert at spot: 396,039.60396 x 1.120 = $443,564 (nearest dollar). At maturity the euro loan is repaid with the receivable.'),
  (5, 'list', 14, 'Complete the ex-post ranking of dollar outcomes at the maturity spot of 1.080.', NULL, '{"fields": [{"label": "The highest dollar outcome among unhedged, forward, and option (net of premium) is the","options": ["forward hedge","put option","unhedged position"]},{"label": "and the unhedged position yields","options": ["$432,000","$440,000","$436,000","$443,564"]}]}'::jsonb, '{"values": ["forward hedge","$432,000"]}'::jsonb, 'Unhedged = 400,000 x 1.080 = $432,000. Forward $440,000. Option net $436,000. Forward ranks highest in this realised-spot scenario; the option still beats unhedged.'),
  (6, 'dnd', 14, 'Classify each instrument by whether it <b>caps downside while leaving upside</b> if the euro strengthens against the dollar.', NULL, '{"items": [{"id": "a","text": "Sell euros forward"},{"id": "b","text": "Buy a euro put option"},{"id": "c","text": "Money-market hedge (borrow euros, convert spot)"},{"id": "d","text": "Remain unhedged"}],"zones": {"upside": "Leaves upside if euro strengthens","locks": "Locks / eliminates upside"}}'::jsonb, '{"placement": {"a": "locks","b": "upside","c": "locks","d": "upside"}}'::jsonb, 'A put is insurance: if the euro strengthens, let it expire and sell at the better spot (net of premium). Forward and money-market hedges fix the rate. Unhedged keeps full upside and full downside.'),
  (7, 'multi', 14, 'Which statements are correct for Munnar''s hedging decision? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply","options": ["The forward sale eliminates transaction exposure on the EUR 400,000 receivable.","The put option''s maximum loss (ignoring time value) is limited to the premium paid.","A stronger euro at maturity would make the unhedged outcome exceed the forward proceeds.","Translation exposure on a foreign subsidiary is hedged by selling this receivable forward.","Money-market and forward hedges both remove upside participation."]}'::jsonb, '{"values": [0,1,2,4]}'::jsonb, 'Forwards offset the receivable''s FX risk; puts limit loss to premium; a stronger euro helps the unhedged position and would beat a short forward; both forward and MM hedges lock the rate. Hedging one receivable does not hedge translation exposure of a subsidiary.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);

-- Case 5: Wayanad Coffee Roasters — cold-store expansion NPV and IRR
with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 2', 'Investment Decisions', 'Wayanad Coffee Roasters — cold-store expansion NPV and IRR', 'Wayanad Coffee Roasters is evaluating a cold-store expansion that would cut spoilage on aged green beans and support a new institutional contract. The project requires an immediate capital outlay and is expected to generate constant annual after-tax operating cash flows for five years, with an after-tax salvage value at the end of year 5 (Exhibit 1).

The company''s hurdle rate for projects of this risk class is 10%. Present-value factors are supplied in Exhibit 2 so that all candidates use the same discounting basis. Ignore inflation and assume cash flows arise at each year-end.', '[{"label": "Exhibit 1 — Project cash flows","caption": "After tax; amounts in $","columns": ["Item","Amount"],"rows": [["Initial outlay (t = 0)","1,200,000"],["Annual after-tax operating cash flow (years 1-5)","320,000"],["After-tax salvage value (year 5, in addition to operating CF)","150,000"],["Project life","5 years"],["Hurdle rate","10%"]],"},{"label": "Exhibit 2 — Present-value factors","caption": "Use these factors; do not interpolate other tables","columns": ["Factor","10%","12%","14%"],"rows": [["PV of $1 (n = 5)","0.6209","0.5674","0.5194"],["PV of annuity $1 (n = 5)","3.7908","3.6048","3.4331"]]}]'::jsonb, 'Hard', 'fets_v2', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'num', 16, 'Calculate the project''s <b>NPV at the 10% hurdle rate</b>.', 'Whole dollars, no commas. Use Exhibit 2 factors.', '{}'::jsonb, '{"value": 106191}'::jsonb, 'PV of operating CFs = 320,000 x 3.7908 = 1,213,056. PV of salvage = 150,000 x 0.6209 = 93,135. NPV = -1,200,000 + 1,213,056 + 93,135 = $106,191.'),
  (2, 'num', 12, 'Calculate the project''s <b>accounting / simple payback period</b> in years (ignore salvage and discounting).', 'Two decimal places.', '{"decimals": true}'::jsonb, '{"value": 3.75,"tolerance": 0.005}'::jsonb, '1,200,000 / 320,000 = 3.75 years.'),
  (3, 'num', 14, 'Calculate the project''s <b>profitability index</b> at 10% (PV of inflows / initial outlay).', 'Two decimal places.', '{"decimals": true}'::jsonb, '{"value": 1.09,"tolerance": 0.005}'::jsonb, 'PV inflows = 1,213,056 + 93,135 = 1,306,191. PI = 1,306,191 / 1,200,000 = 1.0885 ~ 1.09.'),
  (4, 'num', 14, 'Calculate <b>NPV at 12%</b> using Exhibit 2.', 'Whole dollars. Sign: enter as a positive number if NPV is positive.', '{}'::jsonb, '{"value": 38646}'::jsonb, '320,000 x 3.6048 = 1,153,536; 150,000 x 0.5674 = 85,110; NPV = -1,200,000 + 1,153,536 + 85,110 = $38,646.'),
  (5, 'list', 14, 'Using linear interpolation between 12% and 14%, complete the IRR statement.', NULL, '{"fields": [{"label": "NPV at 14% is","options": ["-$23,498","$23,498","-$38,646","$0"]},{"label": "and the interpolated IRR is closest to","options": ["13.2%","12.4%","13.8%","14.0%"]}]}'::jsonb, '{"values": ["-$23,498","13.2%"]}'::jsonb, 'NPV14 = 320,000 x 3.4331 + 150,000 x 0.5194 - 1,200,000 = 1,098,592 + 77,910 - 1,200,000 = -23,498. Interpolate: 12% + 2% x (38,646 / (38,646 + 23,498)) = 12% + 2% x 0.6222 ~ 13.2%.'),
  (6, 'multi', 16, 'Which conclusions follow from the analysis? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply","options": ["At the 10% hurdle rate the project creates shareholder value.","IRR exceeds the 10% hurdle rate.","A profitability index above 1.0 is consistent with a positive NPV.","Payback alone is sufficient to accept the project under shareholder-value criteria.","If the hurdle rate rose to 14%, NPV would turn negative and the project would be rejected."]}'::jsonb, '{"values": [0,1,2,4]}'::jsonb, 'Positive NPV at 10%, IRR ~ 13.2% > 10%, and PI > 1 are aligned accept signals. Payback ignores time value and cash flows beyond recovery, so it is not sufficient alone. At 14% NPV is negative, so the project fails that hurdle.'),
  (7, 'dnd', 14, 'Match each capital-budgeting metric to the description that best fits it.', NULL, '{"items": [{"id": "a","text": "Net present value"},{"id": "b","text": "Internal rate of return"},{"id": "c","text": "Payback period"},{"id": "d","text": "Profitability index"}],"zones": {"abs": "Absolute dollar value added to wealth","rate": "Break-even discount rate on the project''s cash flows","time": "Time to recover the initial outlay from undiscounted CFs","rel": "Present-value bang per dollar invested"}}'::jsonb, '{"placement": {"a": "abs","b": "rate","c": "time","d": "rel"}}'::jsonb, 'NPV measures wealth increase in dollars; IRR is the rate that drives NPV to zero; payback counts recovery time; PI scales PV inflows to outlay for ranking under rationing.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);

-- Case 6: Pathanamthitta Hydro Ventures — WACC and project-finance choice
