with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 2', 'Decision Analysis', 'Alappuzha Coir Exports — cost-volume-profit and an export order', 'Alappuzha Coir Exports manufactures woven coir matting. Its single product sells for $50.00 a unit with variable costs of $30.00, and annual fixed costs are $1,200,000. Practical capacity is 100,000 units a year and the company currently sells 80,000.

A European distributor has approached the company with a one-off order for 15,000 units at $38.00 each. The order would carry additional shipping and export documentation costs of $2.00 a unit; all other variable costs would be unchanged, and no additional fixed costs would be incurred. The distributor sells into markets Alappuzha does not currently serve, and the goods would carry the distributor''s own branding.

The Sales Director opposes the order on the grounds that $38.00 is below the full absorption cost of $45.00 a unit. The Managing Director has asked for a relevant-cost analysis before the Board meets.', '[{"label": "Exhibit 1 — Cost and volume data", "caption": "Current year", "columns": ["Item", "Value"], "rows": [["Selling price per unit", "$50.00"], ["Variable cost per unit", "$30.00"], ["Contribution margin per unit", "$20.00"], ["Annual fixed costs", "$1,200,000"], ["Practical capacity (units)", "100,000"], ["Current sales volume (units)", "80,000"], ["Full absorption cost per unit at current volume", "$45.00"]]}, {"label": "Exhibit 2 — Proposed export order", "caption": "One-off, non-recurring", "columns": ["Item", "Value"], "rows": [["Order quantity (units)", "15,000"], ["Price offered per unit", "$38.00"], ["Additional shipping and documentation per unit", "$2.00"], ["Additional fixed costs", "Nil"], ["Branding", "Distributor''s own"]]}]'::jsonb, 'Medium', 'fets', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'num', 13, 'Calculate the <b>breakeven volume in units</b>.', 'Whole units, no commas.', '{}'::jsonb, '{"value": 60000}'::jsonb, 'Contribution margin = $50.00 − $30.00 = $20.00. Breakeven = $1,200,000 ÷ $20.00 = 60,000 units.'),
  (2, 'num', 13, 'Calculate the volume in units required to earn an operating income of <b>$400,000</b>.', 'Whole units, no commas.', '{}'::jsonb, '{"value": 80000}'::jsonb, '($1,200,000 + $400,000) ÷ $20.00 = 80,000 units — which is exactly the current volume.'),
  (3, 'num', 13, 'Calculate the <b>margin of safety</b> at the current volume, as a percentage of sales.', 'One decimal place. Enter the number only, without a percent sign.', '{"decimals": true}'::jsonb, '{"value": 25.0, "tolerance": 0.06}'::jsonb, '(80,000 − 60,000) ÷ 80,000 = 25.0%. Volume could fall by a quarter before the company makes a loss.'),
  (4, 'num', 13, 'Calculate the <b>degree of operating leverage</b> at the current volume.', 'Two decimal places.', '{"decimals": true}'::jsonb, '{"value": 4.0, "tolerance": 0.01}'::jsonb, 'Total contribution $1,600,000 ÷ operating income $400,000 = 4.00. A 10% change in sales moves operating income by 40%.'),
  (5, 'num', 16, 'Calculate the <b>change in annual operating income</b> if the export order is accepted. Enter the amount as a positive whole number.', 'No dollar sign, no commas. Consider only relevant costs.', '{"direction": false}'::jsonb, '{"value": 90000}'::jsonb, 'Relevant cost per unit = $30.00 + $2.00 = $32.00. Contribution = $38.00 − $32.00 = $6.00 per unit × 15,000 = $90,000 increase. Fixed costs are unchanged, so the $45.00 absorption cost the Sales Director cites is not relevant to this decision.'),
  (6, 'multi', 16, 'Which of the following are legitimate reasons to <b>hesitate</b> over accepting the order? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply", "options": ["Existing customers may learn of the lower price and demand similar terms.", "Accepting sets a reference point for the distributor''s future orders.", "The price of $38.00 is below the full absorption cost of $45.00.", "The order would consume 15,000 units of the 20,000 units of spare capacity.", "The contribution per unit on the order is lower than on normal sales."]}'::jsonb, '{"values": [0, 1, 3]}'::jsonb, 'Price erosion among existing customers and anchoring the distributor''s expectations are real commercial risks, and consuming three-quarters of the spare capacity constrains any better opportunity that arrives later. Comparison with absorption cost is precisely the error the Sales Director made, and a lower contribution per unit is irrelevant so long as it is positive and capacity is idle.'),
  (7, 'mcq', 16, 'Suppose the distributor instead ordered 25,000 units on the same terms. What would the change in operating income be?', NULL, '{"options": ["$50,000 increase", "$150,000 increase", "$50,000 decrease", "No change, because capacity is exceeded"]}'::jsonb, '{"value": "A"}'::jsonb, 'Only 20,000 units of spare capacity exist, so 5,000 units of normal sales would be displaced. Gain = 25,000 × $6.00 = $150,000; loss = 5,000 × $20.00 = $100,000. Net $50,000 increase — still positive, but the opportunity cost of displaced sales has consumed two-thirds of the benefit.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);
