with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 2', 'Financial Statement Analysis', 'Ernakulam Ceramics — ratio analysis and return on equity', 'Ernakulam Ceramics manufactures sanitaryware for the domestic construction market. The Board has asked for an analysis of the year''s results ahead of a refinancing discussion with the company''s bankers.

The summarised income statement is in Exhibit 1 and the relevant balance sheet figures, with both opening and closing positions, in Exhibit 2. Use a 365-day year and average balances wherever an average is appropriate.

The bank has indicated that it monitors two things closely: the company''s ability to meet short-term obligations, and the length of time cash is tied up in the operating cycle. Management believes the return on equity is respectable but has not decomposed it to understand what is actually driving the figure.

All sales are on credit and all purchases are on credit terms with suppliers.', '[{"label": "Exhibit 1 — Income statement", "caption": "Year ended 31 March", "columns": ["Item", "Amount"], "rows": [["Revenue", "$5,000,000"], ["Cost of goods sold", "$3,000,000"], ["Gross profit", "$2,000,000"], ["Operating expenses", "$1,200,000"], ["Operating income", "$800,000"], ["Interest expense", "$100,000"], ["Income before tax", "$700,000"], ["Income tax at 30%", "$210,000"], ["Net income", "$490,000"]]}, {"label": "Exhibit 2 — Balance sheet extracts", "caption": "Opening and closing balances", "columns": ["Item", "1 April (opening)", "31 March (closing)"], "rows": [["Accounts receivable", "$380,000", "$420,000"], ["Inventory", "$550,000", "$650,000"], ["Accounts payable", "$280,000", "$320,000"], ["Total current assets", "—", "$1,400,000"], ["Total current liabilities", "—", "$700,000"], ["Total assets", "$3,800,000", "$4,200,000"], ["Shareholders'' equity", "$1,900,000", "$2,100,000"]]}]'::jsonb, 'Medium', 'fets', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'num', 12, 'Calculate the <b>current ratio</b> at 31 March.', 'Two decimal places.', '{"decimals": true}'::jsonb, '{"value": 2.0, "tolerance": 0.005}'::jsonb, '$1,400,000 ÷ $700,000 = 2.00.'),
  (2, 'num', 14, 'Calculate <b>days sales outstanding</b>, using average receivables.', 'One decimal place. 365-day year.', '{"decimals": true}'::jsonb, '{"value": 29.2, "tolerance": 0.06}'::jsonb, 'Average receivables = $400,000. Receivables turnover = $5,000,000 ÷ $400,000 = 12.50. DSO = 365 ÷ 12.50 = 29.2 days.'),
  (3, 'num', 16, 'Calculate the <b>cash conversion cycle</b> in days.', 'One decimal place. Inventory and payables turn on cost of goods sold.', '{"decimals": true}'::jsonb, '{"value": 65.7, "tolerance": 0.11}'::jsonb, 'Days inventory 73.0 + days sales outstanding 29.2 − days payables 36.5 = 65.7 days. Cash is tied up for roughly two months of every operating cycle.'),
  (4, 'list', 16, 'Complete the DuPont decomposition of return on equity, using average balances.', NULL, '{"fields": [{"label": "Net profit margin is", "options": ["9.8%", "16.0%", "9.0%", "14.0%"]}, {"label": "total asset turnover is", "options": ["1.25", "1.19", "2.50", "0.80"]}, {"label": "and the equity multiplier is", "options": ["2.00", "1.90", "2.10", "0.50"]}]}'::jsonb, '{"values": ["9.8%", "1.25", "2.00"]}'::jsonb, 'Margin $490,000 ÷ $5,000,000 = 9.8%. Asset turnover $5,000,000 ÷ $4,000,000 = 1.25. Equity multiplier $4,000,000 ÷ $2,000,000 = 2.00.'),
  (5, 'num', 12, 'Calculate <b>return on equity</b> as a percentage, using average equity.', 'One decimal place. Enter the number only, without a percent sign.', '{"decimals": true}'::jsonb, '{"value": 24.5, "tolerance": 0.06}'::jsonb, '$490,000 ÷ $2,000,000 = 24.5%, which is also 9.8% × 1.25 × 2.00. Half the return is coming from leverage, not from operations.'),
  (6, 'multi', 16, 'Which of the following would <b>shorten</b> the cash conversion cycle? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply", "options": ["Negotiating longer payment terms with suppliers.", "Offering customers an early settlement discount.", "Increasing inventory to improve product availability.", "Tightening credit approval for new customers.", "Refinancing short-term borrowing with a long-term loan."]}'::jsonb, '{"values": [0, 1, 3]}'::jsonb, 'Longer supplier terms raise days payable, which is subtracted. Early settlement discounts and tighter credit both reduce days sales outstanding. Holding more inventory lengthens the cycle, and refinancing changes the funding of working capital without changing the cycle itself.'),
  (7, 'dnd', 14, 'Classify each ratio by the category it belongs to.', NULL, '{"items": [{"id": "a", "text": "Current ratio"}, {"id": "b", "text": "Inventory turnover"}, {"id": "c", "text": "Equity multiplier"}, {"id": "d", "text": "Return on equity"}, {"id": "e", "text": "Times interest earned"}], "zones": {"liq": "Liquidity", "act": "Activity", "lev": "Leverage", "prof": "Profitability"}}'::jsonb, '{"placement": {"a": "liq", "b": "act", "c": "lev", "d": "prof", "e": "lev"}}'::jsonb, 'Liquidity ratios measure short-term solvency; activity ratios measure how hard assets work; leverage ratios measure the use and burden of debt, which covers both the equity multiplier and interest cover; profitability ratios measure return.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);
with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 2', 'Corporate Finance', 'Kochi Marine Services — cost of capital for a new division', 'Kochi Marine Services operates port logistics terminals and is evaluating entry into offshore survey work, a materially riskier business than its existing operations.

The company''s capital structure and market data are set out in Exhibit 1. Management intends to fund the new division at the same debt-to-equity proportions as the group and treats the current structure as its long-run target.

The Finance Director has proposed appraising the offshore survey project at the group''s weighted average cost of capital. The Chief Executive is uneasy, noting that quoted companies operating purely in offshore survey have equity betas averaging 1.6 against the group''s 1.2.

The corporate tax rate is 30%. Assume debt is issued at par and that the capital asset pricing model holds.', '[{"label": "Exhibit 1 — Capital structure and market data", "caption": "At the valuation date", "columns": ["Item", "Value"], "rows": [["Market value of debt", "$10,000,000"], ["Pre-tax cost of debt", "8.0%"], ["Ordinary shares in issue", "3,000,000"], ["Market price per share", "$10.00"], ["Corporate tax rate", "30%"], ["Risk-free rate", "4.0%"], ["Expected market return", "11.0%"], ["Group equity beta", "1.20"], ["Pure-play equity beta, offshore survey", "1.60"]]}]'::jsonb, 'Hard', 'fets', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'num', 12, 'Calculate the <b>after-tax cost of debt</b> as a percentage.', 'One decimal place. Enter the number only.', '{"decimals": true}'::jsonb, '{"value": 5.6, "tolerance": 0.06}'::jsonb, '8.0% × (1 − 0.30) = 5.6%. Interest is tax-deductible, so the cost to the company is the after-tax figure.'),
  (2, 'num', 14, 'Calculate the <b>group cost of equity</b> using the capital asset pricing model.', 'One decimal place. Enter the number only.', '{"decimals": true}'::jsonb, '{"value": 12.4, "tolerance": 0.06}'::jsonb, '4.0% + 1.20 × (11.0% − 4.0%) = 4.0% + 8.4% = 12.4%.'),
  (3, 'num', 16, 'Calculate the <b>group weighted average cost of capital</b> using market value weights.', 'One decimal place. Enter the number only.', '{"decimals": true}'::jsonb, '{"value": 10.7, "tolerance": 0.06}'::jsonb, 'Equity is 3,000,000 × $10.00 = $30,000,000, so weights are 25% debt and 75% equity. WACC = 25% × 5.6% + 75% × 12.4% = 10.7%.'),
  (4, 'num', 16, 'Calculate the <b>project-specific discount rate</b> for the offshore survey division, using the pure-play beta and the same capital structure.', 'One decimal place. Enter the number only.', '{"decimals": true}'::jsonb, '{"value": 12.8, "tolerance": 0.06}'::jsonb, 'Project cost of equity = 4.0% + 1.60 × 7.0% = 15.2%. Project rate = 25% × 5.6% + 75% × 15.2% = 12.8%, some 2.1 percentage points above the group figure.'),
  (5, 'list', 14, 'Complete the following statement about the Finance Director''s proposal.', NULL, '{"fields": [{"label": "Appraising the offshore project at the group WACC would tend to", "options": ["accept projects that destroy value", "reject projects that create value", "have no systematic effect"]}, {"label": "because the group rate is", "options": ["below the project''s risk-adjusted rate", "above the project''s risk-adjusted rate", "equal to the project''s risk-adjusted rate"]}]}'::jsonb, '{"values": ["accept projects that destroy value", "below the project''s risk-adjusted rate"]}'::jsonb, 'The group rate of 10.7% is below the 12.8% the project''s risk warrants. Discounting risky cash flows too lightly overstates net present value and leads to accepting projects that do not compensate for their risk.'),
  (6, 'multi', 16, 'Why are <b>market value</b> weights preferred to book value weights in a WACC calculation? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply", "options": ["Market values reflect what investors would require to supply capital today.", "Book equity is a historical figure and can differ greatly from market capitalisation.", "Market weights are more stable over time than book weights.", "The cost of each component is itself an expected market return."]}'::jsonb, '{"values": [0, 1, 3]}'::jsonb, 'WACC is a forward-looking opportunity cost, so both the weights and the component costs should be expressed in market terms. Market weights are in fact less stable than book weights, not more — that is a cost of the method, not a reason for it.'),
  (7, 'dnd', 12, 'Classify each source of risk according to whether it is systematic or unsystematic.', NULL, '{"items": [{"id": "a", "text": "A rise in the general level of interest rates"}, {"id": "b", "text": "Loss of the company''s largest single customer"}, {"id": "c", "text": "A national recession reducing port volumes"}, {"id": "d", "text": "A fire at one of the company''s terminals"}], "zones": {"sys": "Systematic risk", "unsys": "Unsystematic risk"}}'::jsonb, '{"placement": {"a": "sys", "b": "unsys", "c": "sys", "d": "unsys"}}'::jsonb, 'Systematic risk affects the whole market and cannot be diversified away — it is what beta measures and what investors are compensated for. Customer loss and fire damage are company-specific and diversifiable, so they carry no risk premium.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);
