delete from public.cbq_cases where source='fets';
with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 1', 'Performance Management', 'Kadalundi Precision Components — variance analysis and a supplier offer', 'Kadalundi Precision Components manufactures the KP-7 valve assembly for the marine equipment industry and produces 40,000 units annually. The company operates a standard absorption costing system; the standard cost card is reproduced in Exhibit 1 and actual results for the year just ended in Exhibit 2.

All materials purchased during the year were used in production, and there was no opening or closing inventory of raw materials or finished goods. Variable overhead is absorbed on direct labour hours.

An external supplier has offered to supply the KP-7 at $76.00 per unit under a one-year contract. If the company ceased production, $240,000 of the annual fixed overhead — a dedicated supervisor''s salary and line insurance — would be avoided. The remainder is general plant overhead that would be reallocated across other product lines. The floor space released could be sublet for $90,000 a year, although no tenant has yet been identified.

The Controller has asked you to analyse the year''s variances and to advise on the offer.', '[{"label": "Exhibit 1 — Standard cost", "caption": "Per KP-7 valve assembly", "columns": ["Cost element", "Quantity", "Rate", "Standard cost"], "rows": [["Direct materials", "2.50 kg", "$12.00", "$30.00"], ["Direct labour", "0.80 hr", "$25.00", "$20.00"], ["Variable overhead", "0.80 hr", "$15.00", "$12.00"], ["Fixed overhead (allocated)", "0.80 hr", "$22.50", "$18.00"], ["Total standard cost", "", "", "$80.00"]]}, {"label": "Exhibit 2 — Actual results", "caption": "Year ended 31 March", "columns": ["Item", "Actual"], "rows": [["Units produced", "40,000"], ["Direct materials purchased and used", "104,000 kg"], ["Total direct materials cost", "$1,300,000"], ["Direct labour hours worked", "33,600 hr"], ["Total direct labour cost", "$865,200"], ["Variable overhead incurred", "$520,000"], ["Fixed overhead incurred", "$735,000"], ["Fixed overhead budgeted", "$720,000"]]}]'::jsonb, 'Hard', 'fets', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'num', 12, 'Calculate the <b>direct materials price variance</b> for the year. Enter the amount as a positive whole number and indicate its direction.', 'No dollar sign, no commas.', '{"direction": true}'::jsonb, '{"value": 52000, "direction": "U"}'::jsonb, 'Actual price = $1,300,000 ÷ 104,000 kg = $12.50. Price variance = 104,000 × ($12.50 − $12.00) = $52,000 unfavourable.'),
  (2, 'num', 12, 'Calculate the <b>direct materials quantity (usage) variance</b> for the year.', 'No dollar sign, no commas.', '{"direction": true}'::jsonb, '{"value": 48000, "direction": "U"}'::jsonb, 'Standard quantity = 40,000 × 2.5 kg = 100,000 kg. Usage variance = (104,000 − 100,000) × $12.00 = $48,000 unfavourable.'),
  (3, 'list', 16, 'Complete the following statement by selecting the appropriate option in each field.', NULL, '{"fields": [{"label": "The direct labour rate variance is", "options": ["$25,200 favourable", "$25,200 unfavourable", "$40,000 unfavourable", "$21,000 unfavourable"]}, {"label": "and the direct labour efficiency variance is", "options": ["$40,000 favourable", "$40,000 unfavourable", "$41,200 unfavourable", "$25,200 unfavourable"]}]}'::jsonb, '{"values": ["$25,200 unfavourable", "$40,000 unfavourable"]}'::jsonb, 'Actual rate = $865,200 ÷ 33,600 = $25.75. Rate variance = 33,600 × ($25.75 − $25.00) = $25,200 U. Standard hours = 40,000 × 0.8 = 32,000. Efficiency variance = (33,600 − 32,000) × $25.00 = $40,000 U.'),
  (4, 'num', 12, 'Calculate the <b>variable overhead efficiency variance</b> for the year.', 'Variable overhead is absorbed on direct labour hours.', '{"direction": true}'::jsonb, '{"value": 24000, "direction": "U"}'::jsonb, '(33,600 − 32,000) × $15.00 = $24,000 unfavourable. The same 1,600 excess hours drive both the labour efficiency and the variable overhead efficiency variance.'),
  (5, 'dnd', 20, 'Classify each item according to whether it is relevant to the decision to continue manufacturing the KP-7 or to buy it from the supplier. <b>All five items must be placed.</b>', NULL, '{"items": [{"id": "a", "text": "Direct materials of $30.00 per unit"}, {"id": "b", "text": "General plant overhead reallocated to other lines"}, {"id": "c", "text": "Avoidable supervisor salary and insurance of $240,000"}, {"id": "d", "text": "Sublease income of $90,000 forgone by continuing"}, {"id": "e", "text": "The unfavourable materials variances reported this year"}], "zones": {"rel": "Relevant to the decision", "irr": "Not relevant to the decision"}}'::jsonb, '{"placement": {"a": "rel", "b": "irr", "c": "rel", "d": "rel", "e": "irr"}}'::jsonb, 'Relevant costs differ between the alternatives. Incremental variable costs and avoidable fixed overhead both cease if production stops, and the forgone sublease is an opportunity cost of continuing. Reallocated general overhead is incurred either way, and this year''s variances are sunk.'),
  (6, 'num', 16, 'Calculate the <b>relevant cost per unit of manufacturing</b> the KP-7 internally.', 'Include the opportunity cost. Two decimal places.', '{"decimals": true}'::jsonb, '{"value": 70.25, "tolerance": 0.005}'::jsonb, 'Variable cost $62.00 + avoidable fixed overhead $240,000÷40,000 = $6.00 + forgone sublease $90,000÷40,000 = $2.25, giving $70.25. Against the supplier''s $76.00, manufacturing is cheaper by $5.75 per unit, or $230,000 a year.'),
  (7, 'multi', 12, 'Which of the following would cast doubt on a recommendation to continue manufacturing internally? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply", "options": ["The supplier''s price is fixed for one year only and may rise on renewal.", "No tenant has yet been identified for the released floor space.", "Dismantling the line would make a later reversal of the decision costly.", "The allocated fixed overhead of $18.00 per unit exceeds the avoidable amount.", "Direct labour worked 1,600 hours more than standard during the year."]}'::jsonb, '{"values": [0, 1]}'::jsonb, 'A price rise on renewal and an unsecured sublease would each erode the $230,000 advantage. Dismantling costs argue for continuing, not against it. The overhead allocation and the labour variance describe the current position rather than risks to the recommendation.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);
