with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 1', 'Planning, Budgeting and Forecasting', 'Malabar Foods — March cash budget', 'Malabar Foods packs and distributes spice blends across south India. The Treasurer prepares a rolling three-month cash budget and is finalising the figures for March.

Sales are made entirely on credit. Historically 40% of a month''s sales are collected in the month of sale, 50% in the following month and 8% in the second following month; the remaining 2% proves uncollectible and is written off.

Purchases in any month equal 60% of the <em>following</em> month''s budgeted sales. Suppliers are paid 30% in the month of purchase and 70% in the month after.

Fixed cash operating expenses run at $220,000 a month and are paid as incurred. Depreciation of $45,000 a month is charged in the income statement but is not a cash flow. The cash balance at 1 March is $150,000, and the Board requires a minimum month-end balance of $100,000. Any shortfall is met by drawing on a revolving credit facility.

Actual and budgeted sales are set out in Exhibit 1.', '[{"label": "Exhibit 1 — Sales", "caption": "Actual to February, budgeted from March", "columns": ["Month", "Sales"], "rows": [["December (actual)", "$700,000"], ["January (actual)", "$800,000"], ["February (actual)", "$900,000"], ["March (budget)", "$1,050,000"], ["April (budget)", "$1,200,000"]]}, {"label": "Exhibit 2 — Cash policy", "caption": "Board-approved treasury parameters", "columns": ["Parameter", "Value"], "rows": [["Cash balance at 1 March", "$150,000"], ["Minimum month-end balance", "$100,000"], ["Fixed cash operating expenses per month", "$220,000"], ["Monthly depreciation charge", "$45,000"], ["Collection pattern", "40% / 50% / 8%, 2% written off"], ["Supplier payment pattern", "30% in month, 70% following month"]]}]'::jsonb, 'Medium', 'fets', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'num', 15, 'Calculate the <b>total cash collected from customers in March</b>.', 'Whole dollars, no commas.', '{}'::jsonb, '{"value": 934000}'::jsonb, '40% × $1,050,000 + 50% × $900,000 + 8% × $800,000 = $420,000 + $450,000 + $64,000 = $934,000.'),
  (2, 'num', 15, 'Calculate the <b>total cash paid to suppliers in March</b>.', 'March purchases are based on April''s budgeted sales.', '{}'::jsonb, '{"value": 657000}'::jsonb, 'March purchases = 60% × $1,200,000 = $720,000; February purchases = 60% × $1,050,000 = $630,000. Payments = 30% × $720,000 + 70% × $630,000 = $657,000.'),
  (3, 'num', 15, 'Calculate the <b>cash balance at 31 March</b>, before any drawing on the credit facility.', 'Remember which charges are not cash flows.', '{}'::jsonb, '{"value": 207000}'::jsonb, '$150,000 + $934,000 − $657,000 − $220,000 = $207,000. Depreciation is excluded — it is not a cash flow.'),
  (4, 'list', 14, 'Complete the following statement about the March position.', NULL, '{"fields": [{"label": "At 31 March the company", "options": ["will need to draw on the facility", "will not need to draw on the facility"]}, {"label": "and the balance exceeds the required minimum by", "options": ["$107,000", "$207,000", "$57,000", "$207,000 shortfall"]}]}'::jsonb, '{"values": ["will not need to draw on the facility", "$107,000"]}'::jsonb, 'The closing balance of $207,000 exceeds the $100,000 minimum by $107,000, so no drawing is required.'),
  (5, 'dnd', 14, 'Classify each schedule according to whether it forms part of the <b>operating budget</b> or the <b>financial budget</b>.', NULL, '{"items": [{"id": "a", "text": "Sales budget"}, {"id": "b", "text": "Cash budget"}, {"id": "c", "text": "Direct materials purchases budget"}, {"id": "d", "text": "Capital expenditure budget"}, {"id": "e", "text": "Budgeted income statement"}, {"id": "f", "text": "Budgeted balance sheet"}], "zones": {"op": "Operating budget", "fin": "Financial budget"}}'::jsonb, '{"placement": {"a": "op", "b": "fin", "c": "op", "d": "fin", "e": "op", "f": "fin"}}'::jsonb, 'The operating budget builds to the budgeted income statement through sales, production, materials, labour and overhead. The financial budget covers cash, capital spending and the budgeted balance sheet.'),
  (6, 'mcq', 15, 'If collections were to slow to 30% in the month of sale, 50% in the following month and 18% in the second following month, with bad debts unchanged at 2%, what would the 31 March cash balance become?', NULL, '{"options": ["$182,000", "$207,000", "$157,000", "$232,000"]}'::jsonb, '{"value": "A"}'::jsonb, 'Collections fall to 30% × $1,050,000 + 50% × $900,000 + 18% × $800,000 = $909,000, a reduction of $25,000. The closing balance falls from $207,000 to $182,000 — still above the minimum, but the margin narrows sharply.'),
  (7, 'multi', 12, 'Which of the following are characteristics of <b>participative</b> budgeting? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply", "options": ["Targets are set by the managers who will be held accountable for them.", "It tends to improve motivation and acceptance of the budget.", "It creates a risk of budgetary slack.", "It is normally faster to prepare than an imposed budget.", "It removes the need for senior management review."]}'::jsonb, '{"values": [0, 1, 2]}'::jsonb, 'Participative budgeting involves the accountable managers in setting targets, which improves buy-in but invites slack. It is slower than an imposed budget, not faster, and senior review remains essential precisely because of the slack risk.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);
with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 1', 'Cost Management', 'Beypore Marine Fabricators — plantwide rate versus activity-based costing', 'Beypore Marine Fabricators builds two products: a Standard hull, produced in long runs, and a Custom hull built to order in small batches. Annual volumes are 8,000 Standard and 2,000 Custom.

Manufacturing overhead of $1,200,000 a year is presently absorbed using a single plantwide rate based on direct labour hours. The Standard hull requires 0.5 direct labour hours per unit and the Custom hull 2.0 hours.

Competitors have recently undercut Beypore''s price on the Standard hull, while the company continues to win Custom work comfortably on price. The Managing Director suspects the costing system is distorting the picture and has asked for an activity-based analysis. The Cost Accountant has identified three activity cost pools and their drivers, set out in Exhibit 2.', '[{"label": "Exhibit 1 — Volumes and labour", "caption": "Annual", "columns": ["Product", "Units", "Direct labour hours per unit", "Total direct labour hours"], "rows": [["Standard hull", "8,000", "0.5", "4,000"], ["Custom hull", "2,000", "2.0", "4,000"], ["Total", "10,000", "", "8,000"]]}, {"label": "Exhibit 2 — Activity cost pools", "caption": "Total overhead $1,200,000", "columns": ["Activity pool", "Pool cost", "Cost driver", "Standard hull", "Custom hull"], "rows": [["Machine setups", "$360,000", "setups", "40", "160"], ["Machining", "$600,000", "machine hours", "20,000", "10,000"], ["Inspection", "$240,000", "inspections", "200", "600"]]}]'::jsonb, 'Medium', 'fets', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'num', 13, 'Calculate the <b>plantwide overhead rate per direct labour hour</b>.', 'Two decimal places.', '{"decimals": true}'::jsonb, '{"value": 150.0, "tolerance": 0.005}'::jsonb, '$1,200,000 ÷ 8,000 direct labour hours = $150.00 per hour.'),
  (2, 'num', 13, 'Under the <b>plantwide rate</b>, calculate the overhead absorbed per <b>Standard</b> hull.', 'Two decimal places.', '{"decimals": true}'::jsonb, '{"value": 75.0, "tolerance": 0.005}'::jsonb, '0.5 hours × $150.00 = $75.00 per Standard hull.'),
  (3, 'num', 16, 'Under <b>activity-based costing</b>, calculate the overhead assigned per <b>Custom</b> hull.', 'Two decimal places. Work each pool''s driver rate first.', '{"decimals": true}'::jsonb, '{"value": 334.0, "tolerance": 0.01}'::jsonb, 'Setups $360,000 ÷ 200 = $1,800 each; 160 × $1,800 ÷ 2,000 = $144.00. Machining $600,000 ÷ 30,000 = $20.00 per hour; 10,000 × $20 ÷ 2,000 = $100.00. Inspection $240,000 ÷ 800 = $300 each; 600 × $300 ÷ 2,000 = $90.00. Total $334.00 per Custom hull.'),
  (4, 'num', 16, 'By how much per unit does the plantwide rate <b>undercost</b> the Custom hull?', 'Two decimal places.', '{"decimals": true}'::jsonb, '{"value": 34.0, "tolerance": 0.01}'::jsonb, 'ABC assigns $334.00 against the plantwide $300.00, so the Custom hull is undercosted by $34.00 per unit. The Standard hull is correspondingly overcosted by $8.50.'),
  (5, 'dnd', 14, 'Match each activity cost pool to the driver that best reflects what causes its cost.', NULL, '{"items": [{"id": "a", "text": "Machine setup costs"}, {"id": "b", "text": "Machine power and maintenance"}, {"id": "c", "text": "Quality inspection"}, {"id": "d", "text": "Factory building rent"}], "zones": {"batch": "Batch-level driver", "unit": "Unit-level driver", "fac": "Facility-level — no meaningful driver"}}'::jsonb, '{"placement": {"a": "batch", "b": "unit", "c": "batch", "d": "fac"}}'::jsonb, 'Setups and inspections are incurred per batch regardless of batch size. Machine power varies with machine hours, a unit-level driver. Building rent supports the plant as a whole and is arbitrarily allocated under any system.'),
  (6, 'multi', 16, 'Why does activity-based costing produce a materially different answer here? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply", "options": ["The Custom hull consumes batch-level activities out of all proportion to its labour hours.", "The plantwide rate assumes overhead is driven solely by direct labour hours.", "Activity-based costing assigns more total overhead than the plantwide method.", "The Standard hull''s high volume absorbs overhead it does not cause.", "Direct labour is the largest single element of the Custom hull''s cost."]}'::jsonb, '{"values": [0, 1, 3]}'::jsonb, 'ABC redistributes the same $1,200,000 — it never assigns more in total, which rules out the third option. The distortion arises because the low-volume Custom hull consumes setups and inspections far out of proportion to its labour hours, while the high-volume Standard hull absorbs overhead it does not cause.'),
  (7, 'mcq', 12, 'What does the analysis suggest about Beypore''s pricing?', NULL, '{"options": ["The Standard hull may be priced above the level its true cost requires, and the Custom hull below it.", "Both products are priced too low and a general increase is warranted.", "The Custom hull should be discontinued because it is unprofitable.", "Pricing should not change, since total overhead recovered is identical under both methods."]}'::jsonb, '{"value": "A"}'::jsonb, 'Overcosting the Standard hull inflates its price and explains why competitors undercut it; undercosting the Custom hull explains why Beypore wins that work easily. Discontinuation cannot be judged without contribution data, and identical total recovery says nothing about whether individual prices are right.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);
