with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 1', 'Cost Management', 'Kollam Cashew Processors — FIFO process costing', 'Kollam Cashew Processors runs a single roasting department that converts shelled cashews into packaged kernels. The department uses a <b>FIFO</b> process-costing system. Materials are added at the start of the process; conversion costs are incurred evenly.

Production and cost data for May are set out in Exhibits 1 and 2. There is no spoilage. The Cost Accountant has asked you to compute equivalent units, cost per equivalent unit, and the cost of production report figures the Board pack requires.', '[{"label": "Exhibit 1 — Physical flow (units)","caption": "Roasting department, May","columns": ["Description","Units"],"rows": [["Opening WIP (100% materials, 40% conversion)","5,000"],["Started during May","25,000"],["Completed and transferred out","22,000"],["Ending WIP (100% materials, 25% conversion)","8,000"]]},{"label": "Exhibit 2 — Costs","caption": "Roasting department, May","columns": ["Cost element","Opening WIP","Added in May"],"rows": [["Materials","$40,000","$200,000"],["Conversion","$16,000","$154,000"],["Total","$56,000","$354,000"]]}]'::jsonb, 'Hard', 'fets_v2', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'num', 12, 'Under FIFO, calculate <b>equivalent units for materials</b> for May.', 'Whole units. Materials are added at the start of the process.', '{}'::jsonb, '{"value": 25000}'::jsonb, 'Opening WIP already 100% complete for materials, so 0 EU to finish it. Started and completed = 22,000 - 5,000 = 17,000. Ending WIP = 8,000 x 100% = 8,000. EU materials = 0 + 17,000 + 8,000 = 25,000.'),
  (2, 'num', 12, 'Under FIFO, calculate <b>equivalent units for conversion</b> for May.', 'Whole units.', '{}'::jsonb, '{"value": 22000}'::jsonb, 'To complete opening: 5,000 x (1 - 0.40) = 3,000. Started and completed = 17,000. Ending WIP = 8,000 x 25% = 2,000. EU conversion = 3,000 + 17,000 + 2,000 = 22,000.'),
  (3, 'list', 16, 'Complete the statement of cost per equivalent unit (FIFO).', NULL, '{"fields": [{"label": "Materials cost per equivalent unit is","options": ["$8.00","$9.60","$7.00","$8.16"]},{"label": "and conversion cost per equivalent unit is","options": ["$7.00","$8.00","$7.72","$6.16"]}]}'::jsonb, '{"values": ["$8.00","$7.00"]}'::jsonb, 'Materials: $200,000 / 25,000 = $8.00. Conversion: $154,000 / 22,000 = $7.00. FIFO uses only costs added this period in the rate calculation.'),
  (4, 'num', 16, 'Calculate the <b>total cost of units completed and transferred out</b> in May under FIFO.', 'Whole dollars, no commas.', '{}'::jsonb, '{"value": 332000}'::jsonb, 'Opening WIP costs $56,000 + conversion to finish opening 3,000 x $7 = $21,000 + started-and-completed 17,000 x ($8 + $7) = $255,000 = $332,000.'),
  (5, 'num', 14, 'Calculate the <b>cost of ending work in process</b> at 31 May.', 'Whole dollars, no commas.', '{}'::jsonb, '{"value": 78000}'::jsonb, 'Materials 8,000 x $8 = $64,000 + conversion 2,000 x $7 = $14,000 = $78,000. Check: $56,000 + $354,000 = $410,000; $332,000 + $78,000 = $410,000.'),
  (6, 'dnd', 16, 'Classify each statement as true of <b>FIFO</b> process costing, <b>weighted-average</b> process costing, or <b>both</b>.', NULL, '{"items": [{"id": "a","text": "Separates work done in the prior period from work done this period"},{"id": "b","text": "Blends opening WIP costs into the current-period unit cost"},{"id": "c","text": "Requires a physical-flow reconciliation of units"},{"id": "d","text": "Computes equivalent units only for work performed this period"}],"zones": {"fifo": "FIFO only","wa": "Weighted-average only","both": "Both methods"}}'::jsonb, '{"placement": {"a": "fifo","b": "wa","c": "both","d": "fifo"}}'::jsonb, 'FIFO isolates prior-period work and costs; weighted average merges opening costs into the unit rate. Both methods begin with a physical-flow (units) reconciliation.'),
  (7, 'mcq', 14, 'If the department had instead used weighted-average costing, which figure would change?', NULL, '{"options": ["Equivalent units for materials and conversion, and therefore cost per EU and the cost assignment","Physical units completed and transferred out","Total costs to account for ($410,000)","The fact that materials are added at the start of the process"]}'::jsonb, '{"value": "A"}'::jsonb, 'Weighted average redefines EU (opening + started work counted together) and folds opening costs into the rate, changing cost per EU and the assignment. Physical completions and total costs to account for are method-independent; material timing is a process fact.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);

-- Case 3: Kozhikode Spices Limited — inventory valuation and revenue cut-off
with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 1', 'External Financial Reporting', 'Kozhikode Spices Limited — inventory valuation and revenue cut-off', 'Kozhikode Spices Limited exports ground spice blends and holds both owned inventory and goods placed with distributors on consignment. The year-end is 31 March. The Financial Controller is finalising inventory valuation and revenue cut-off and has given you the schedules in Exhibits 1 and 2.

Inventory is measured at the lower of cost and net realisable value under Ind AS 2 / IAS 2. Revenue is recognised under Ind AS 115 / IFRS 15 when control transfers. Management has proposed recognising a bill-and-hold arrangement described in Exhibit 2 and is seeking confirmation that the criteria are met.', '[{"label": "Exhibit 1 — Inventory positions at 31 March","caption": "Before year-end adjustments","columns": ["Line","Description","Cost","Estimated NRV","Notes"],"rows": [["1","Cardamom blend — finished goods (owned warehouse)","$120,000","$95,000","Oversupply; slow moving"],["2","Pepper grind — finished goods on consignment at retail distributor","$80,000","$110,000","Distributor has not sold to end customers"],["3","Turmeric powder — finished goods","$60,000","$72,000","Normal demand"],["4","Raw black pepper — raw materials","$45,000","$40,000","Market price decline"]]},{"label": "Exhibit 2 — Revenue and cut-off items","caption": "Transactions under review","columns": ["Item","Detail"],"rows": [["Bill-and-hold Order BH-17","Invoice $150,000 dated 28 March; customer requested delay of shipment until 12 April for warehouse space; goods segregated, ready, and cannot be redirected; customer accepted billing and risk"],["Shipment S-904","Goods costing $28,000, invoiced $40,000, loaded on carrier 31 March under FOB shipping point terms; arrived at customer 2 April"],["Shipment S-911","Goods costing $18,000, invoiced $26,000, still in Kozhikode warehouse at close of 31 March; FOB destination; delivered 3 April"],["Consignment sales report","Distributor sold $35,000 (cost $22,000) of consigned pepper grind to end customers in March; remittance due April"]]}]'::jsonb, 'Hard', 'fets_v2', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'num', 12, 'Calculate the <b>total write-down to NRV</b> required for inventory lines 1 and 4 combined.', 'Whole dollars. Write down only where NRV is below cost.', '{}'::jsonb, '{"value": 30000}'::jsonb, 'Line 1: $120,000 - $95,000 = $25,000. Line 4: $45,000 - $40,000 = $5,000. Total write-down $30,000. Lines 2 and 3 need no write-down (NRV >= cost).'),
  (2, 'num', 14, 'After the NRV adjustments and after removing the cost of consignment goods sold in March, what is the <b>carrying amount of inventory</b> that should appear on the 31 March statement of financial position?', 'Start from the four lines'' costs, adjust, then remove sold consignment cost.', '{}'::jsonb, '{"value": 253000}'::jsonb, 'Unadjusted costs $120k+$80k+$60k+$45k = $305,000. Less NRV write-downs $30,000 = $275,000. Less cost of consignment sold in March $22,000 = carrying amount $253,000. (Remaining consignment $58,000 stays in Kozhikode''s inventory until sold to end customers.)'),
  (3, 'list', 14, 'Complete the statement on consignment accounting.', NULL, '{"fields": [{"label": "Goods on consignment at the distributor (unsold to end customers) are reported as inventory of","options": ["Kozhikode Spices Limited","the retail distributor","neither party until cash is remitted","both parties at 50% each"]},{"label": "and revenue on the March consignment sales report should be recognised by Kozhikode of","options": ["$35,000","$80,000","$22,000","$0 until remittance arrives"]}]}'::jsonb, '{"values": ["Kozhikode Spices Limited","$35,000"]}'::jsonb, 'Under a consignment arrangement control does not pass until sale to the end customer. Unsold consigned goods remain Kozhikode''s inventory; the $35,000 sold in March is Kozhikode revenue (with related cost $22,000).'),
  (4, 'multi', 16, 'Which of the following support recognising revenue on bill-and-hold Order BH-17 at 31 March? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply","options": ["The reason for the hold is substantive and requested by the customer.","The goods are separately identified as the customer''s and ready for transfer.","Kozhikode retains the ability to redirect the goods to another customer if demand picks up.","The customer has accepted the billing and the related risks.","An invoice was issued before the reporting date."]}'::jsonb, '{"values": [0,1,3]}'::jsonb, 'IFRS 15 bill-and-hold criteria require a substantive customer-requested reason, separate identification, readiness for transfer, and that the entity cannot use the goods or redirect them. Issuing an invoice alone is not sufficient; redirectability would defeat the criteria.'),
  (5, 'dnd', 16, 'For each shipment, decide whether revenue is recognised in the year ended 31 March.', NULL, '{"items": [{"id": "a","text": "Shipment S-904 (FOB shipping point, loaded 31 March)"},{"id": "b","text": "Shipment S-911 (FOB destination, still in warehouse 31 March)"},{"id": "c","text": "Consignment sales to end customers reported for March"},{"id": "d","text": "Unsold consignment goods still at the distributor"}],"zones": {"yes": "Recognise revenue in year ended 31 March","no": "Do not recognise revenue yet"}}'::jsonb, '{"placement": {"a": "yes","b": "no","c": "yes","d": "no"}}'::jsonb, 'FOB shipping point transfers control on loading — S-904 is March revenue. FOB destination waits for delivery — S-911 is April. Consignment revenue follows end-customer sales; unsold consignment is not revenue.'),
  (6, 'num', 14, 'Calculate <b>total revenue</b> that should be recognised from Exhibit 2 items in the year ended 31 March (BH-17, S-904, S-911, consignment).', 'Whole dollars. Apply the cut-off and bill-and-hold conclusions from prior tasks.', '{}'::jsonb, '{"value": 225000}'::jsonb, 'BH-17 $150,000 (criteria met) + S-904 $40,000 + consignment $35,000 = $225,000. S-911 $26,000 is excluded (FOB destination, not delivered).'),
  (7, 'mcq', 14, 'If management refused the NRV write-down on line 1 only, by how much would pre-tax income for the year be overstated?', NULL, '{"options": ["$25,000","$30,000","$5,000","$120,000"]}'::jsonb, '{"value": "A"}'::jsonb, 'Omitting the $25,000 cardamom write-down overstates inventory and pre-tax income by $25,000. The $5,000 raw-pepper write-down is a separate line.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);

-- Case 4: Munnar Tea Estates — euro receivable and hedge selection
