with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 2', 'Corporate Finance', 'Pathanamthitta Hydro Ventures — WACC and project-finance choice', 'Pathanamthitta Hydro Ventures operates small hydropower plants and is considering a run-of-river project in a seismically active catchment — materially riskier than the company''s existing portfolio. Capital-structure and market data are in Exhibit 1.

The CFO proposes discounting the project at the group WACC. The Board''s independent director prefers a pure-play beta. Separately, a consortium of banks has offered a non-recourse project-finance package (Exhibit 2) that would ring-fence the asset. The corporate tax rate is 25%. Assume CAPM holds and debt is at par.', '[{"label": "Exhibit 1 — Group capital market data","caption": "At the valuation date","columns": ["Item","Value"],"rows": [["Market value of debt","$20,000,000"],["Pre-tax cost of debt (group)","7.0%"],["Ordinary shares in issue","4,000,000"],["Market price per share","$15.00"],["Corporate tax rate","25%"],["Risk-free rate","3.5%"],["Expected market return","10.5%"],["Group equity beta","1.10"],["Pure-play equity beta (run-of-river peers)","1.40"]]},{"label": "Exhibit 2 — Project-finance offer","caption": "Non-recourse package for the new plant","columns": ["Item","Value"],"rows": [["Target project gearing (debt / total value)","60%"],["Pre-tax project debt rate","8.0%"],["Sponsor required return on project equity","15.0%"],["Recourse to Pathanamthitta''s other assets","None"]]}]'::jsonb, 'Hard', 'fets_v2', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'num', 12, 'Calculate the group''s <b>after-tax cost of debt</b> as a percentage.', 'Two decimal places. Enter the number only.', '{"decimals": true}'::jsonb, '{"value": 5.25,"tolerance": 0.005}'::jsonb, '7.0% x (1 - 0.25) = 5.25%.'),
  (2, 'num', 14, 'Calculate the <b>group cost of equity</b> using CAPM.', 'One decimal place. Enter the number only.', '{"decimals": true}'::jsonb, '{"value": 11.2,"tolerance": 0.06}'::jsonb, '3.5% + 1.10 x (10.5% - 3.5%) = 3.5% + 7.7% = 11.2%.'),
  (3, 'num', 14, 'Calculate the <b>group WACC</b> using market-value weights.', 'One decimal place. Enter the number only.', '{"decimals": true}'::jsonb, '{"value": 9.7,"tolerance": 0.06}'::jsonb, 'Equity MV = 4,000,000 x $15 = $60,000,000; total capital $80,000,000; weights 25% debt / 75% equity. WACC = 0.25 x 5.25% + 0.75 x 11.2% = 9.7125% ~ 9.7%.'),
  (4, 'num', 16, 'Calculate the <b>project-specific WACC</b> using the pure-play beta and the group''s capital structure.', 'One decimal place. Enter the number only.', '{"decimals": true}'::jsonb, '{"value": 11.3,"tolerance": 0.06}'::jsonb, 'Project Ke = 3.5% + 1.40 x 7.0% = 13.3%. Project WACC = 0.25 x 5.25% + 0.75 x 13.3% = 11.2875% ~ 11.3%.'),
  (5, 'list', 14, 'Complete the statement comparing discount rates.', NULL, '{"fields": [{"label": "The project-finance WACC implied by Exhibit 2 is","options": ["9.6%","11.3%","9.7%","15.0%"]},{"label": "and relative to the pure-play corporate-structure project WACC it is","options": ["lower","higher","the same"]}]}'::jsonb, '{"values": ["9.6%","lower"]}'::jsonb, 'PF WACC = 0.60 x 6.0% + 0.40 x 15.0% = 9.6%, which is below the 11.3% pure-play corporate-structure rate because of heavier cheap debt weight.'),
  (6, 'multi', 14, 'Which statements are correct? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply","options": ["Discounting the project at the group WACC would tend to accept projects that destroy value.","Non-recourse debt limits lenders'' claim to the project cash flows and collateral.","A lower PF WACC than the pure-play corporate-structure WACC automatically means lower operating risk.","Sponsor equity in a highly geared SPV typically demands a higher return than unlevered peer equity.","Using group WACC for a riskier project is equivalent to applying the pure-play adjustment."]}'::jsonb, '{"values": [0,1,3]}'::jsonb, 'Group rate too low causes bad accepts; non-recourse is core to PF; levered sponsor equity demands higher return. Lower PF WACC reflects financing, not lower operating risk; group WACC is not a pure-play fix.'),
  (7, 'dnd', 16, 'Classify each statement as true of <b>corporate WACC appraisal</b>, <b>project finance</b>, or <b>both</b>.', NULL, '{"items": [{"id": "a","text": "Applies the group''s target market-value capital structure"},{"id": "b","text": "Debt is typically non-recourse to the sponsor''s other assets"},{"id": "c","text": "Interest tax shield enters via the after-tax cost of debt"},{"id": "d","text": "Can support higher gearing against ring-fenced project cash flows"},{"id": "e","text": "Should reflect the project''s operating risk, not only the firm''s average risk"}],"zones": {"corp": "Corporate / group WACC appraisal","pf": "Project finance","both": "Both"}}'::jsonb, '{"placement": {"a": "corp","b": "pf","c": "both","d": "pf","e": "both"}}'::jsonb, 'Corporate appraisal applies group target weights; PF uses non-recourse debt and often higher gearing on ring-fenced cash flows. Both use after-tax debt cost, and both should reflect the project''s operating risk.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);
