-- CBQ cases v2 (source=fets_v2). INSERT only — does NOT delete existing cases.
-- Generated for CoStudy CMA-style CBQ. 6 cases x 7 tasks.

-- Case 1: Palakkad FinTech Services — IT general controls and fraud risk
with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 1', 'Internal Controls', 'Palakkad FinTech Services — IT general controls and fraud risk', 'Palakkad FinTech Services operates a regional digital-payments platform that settles merchant collections for more than 4,000 Kerala retailers. Settlements are posted overnight by an automated batch job; exceptions are cleared the next morning by the Operations team.

During a routine review the Internal Audit Manager identified several control weaknesses (Exhibit 1) and has asked you to evaluate them against the fraud triangle and against IT general-control expectations. Separately, a junior settlement clerk was found to have overridden an exception that delayed a Rs 2,400,000 remittance; the override was later reversed, but the incident has raised Board concern.

The company applies a COSO-based control framework. Management estimates that an undetected fraudulent settlement diversion lasting one month would expose roughly Rs 18,000,000 of platform float (Exhibit 2).', '[{"label": "Exhibit 1 — Control observations","caption": "Internal audit findings, quarter ended 30 June","columns": ["Ref","Observation"],"rows": [["A1","Three Operations staff share a single privileged OS login for the settlement server"],["A2","Change tickets to the batch settlement code are approved by the same developer who writes them"],["A3","Exception overrides require a second password, but the password is posted on a shared whiteboard"],["A4","Monthly access reviews of the settlement application have not been performed for eight months"],["A5","Night-shift supervisors are paid a bonus tied solely to clearing all exceptions before 09:00"]]},{"label": "Exhibit 2 — Float and incident data","caption": "Management estimates","columns": ["Item","Amount / detail"],"rows": [["Average month-end platform float at risk","Rs 18,000,000"],["Estimated probability of a successful diversion if A1-A3 remain unremediated","8%"],["Expected detection lag if A4 remains unremediated","45 days"],["Override incident amount (later reversed)","Rs 2,400,000"],["Annual cost of proposed privileged-access management tool","Rs 720,000"]]}]'::jsonb, 'Hard', 'fets_v2', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'dnd', 16, 'Place each observation against the element of the <b>fraud triangle</b> it most directly increases. <b>All five must be placed.</b>', NULL, '{"items": [{"id": "a","text": "A1 — shared privileged OS login"},{"id": "b","text": "A2 — developer self-approves change tickets"},{"id": "c","text": "A3 — override password on a whiteboard"},{"id": "d","text": "A4 — access reviews not performed for eight months"},{"id": "e","text": "A5 — bonus tied solely to clearing exceptions by 09:00"}],"zones": {"opp": "Opportunity","press": "Pressure / incentive","rat": "Rationalisation"}}'::jsonb, '{"placement": {"a": "opp","b": "opp","c": "opp","d": "opp","e": "press"}}'::jsonb, 'Shared credentials, self-approved changes, a public override password and unreviewed access all expand the chance to commit and conceal fraud — opportunity. The 09:00 bonus creates a performance incentive that can pressure staff to clear exceptions improperly. None of the findings primarily describes rationalisation.'),
  (2, 'multi', 14, 'Which of the following are <b>IT general controls</b> rather than application controls? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply","options": ["Privileged operating-system access management on the settlement server","Program-change approval and segregation for the batch settlement code","A field edit that rejects a settlement amount exceeding the merchant''s daily limit","Periodic user-access reviews for the settlement application","An automated three-way match of invoice, receipt and purchase order inside the AP module"]}'::jsonb, '{"values": [0,1,3]}'::jsonb, 'OS access, change management and access reviews are ITGCs that support the reliability of the processing environment. Field edits and three-way matching are application controls embedded in specific business processes.'),
  (3, 'num', 14, 'Calculate the <b>expected annual loss</b> from an undetected diversion if observations A1-A3 remain unremediated, using the float and probability in Exhibit 2. Ignore the detection lag for this task.', 'Whole rupees, no commas or currency symbol.', '{}'::jsonb, '{"value": 1440000}'::jsonb, 'Rs 18,000,000 x 8% = Rs 1,440,000 expected annual loss.'),
  (4, 'list', 14, 'Complete the following statement about the override incident.', NULL, '{"fields": [{"label": "The shared whiteboard password primarily represents a failure of","options": ["segregation of duties","physical and logical access control","input validation","backup and recovery"]},{"label": "and the fact that the override was later reversed means the residual financial misstatement was","options": ["Rs 2,400,000","nil for the reported period once reversed","Rs 18,000,000","Rs 720,000"]}]}'::jsonb, '{"values": ["physical and logical access control","nil for the reported period once reversed"]}'::jsonb, 'Posting a second-factor password publicly defeats logical access control. Because the override was reversed, the financial statements for the period do not retain a Rs 2,400,000 misstatement — though the control failure itself remains a significant deficiency.'),
  (5, 'mcq', 14, 'Relative to the expected annual loss calculated earlier, is the proposed privileged-access management tool cost-justified on a pure expected-loss basis?', NULL, '{"options": ["Yes — annual tool cost of Rs 720,000 is below the Rs 1,440,000 expected loss.","No — the tool costs more than the expected loss.","Indifferent — tool cost equals expected loss.","Cannot tell — detection lag must be known first."]}'::jsonb, '{"value": "A"}'::jsonb, 'Rs 720,000 < Rs 1,440,000, so on a pure expected-loss comparison the tool is cost-justified. (A fuller business case would also weigh residual risk and qualitative regulatory exposure.)'),
  (6, 'dnd', 14, 'Classify each proposed remediation as primarily <b>preventive</b> or <b>detective</b>.', NULL, '{"items": [{"id": "a","text": "Issue unique privileged credentials and enforce MFA on the settlement server"},{"id": "b","text": "Require independent CAB approval before production changes go live"},{"id": "c","text": "Resume monthly user-access reviews with exception reporting to Internal Audit"},{"id": "d","text": "Reintroduce an overnight exception log reviewed the next morning by a non-ops supervisor"}],"zones": {"prev": "Preventive","det": "Detective"}}'::jsonb, '{"placement": {"a": "prev","b": "prev","c": "det","d": "det"}}'::jsonb, 'Unique credentials, MFA and independent change approval stop unauthorised acts before they occur. Access reviews and exception-log reviews discover problems after the fact.'),
  (7, 'multi', 14, 'Which statements about the fraud triangle and this case are correct? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply","options": ["Removing opportunity alone can still leave residual fraud risk if pressure remains high.","A5 increases pressure even though it does not itself create an access path.","Rationalisation is evidenced directly by the shared OS login in A1.","IT general controls primarily address opportunity by limiting unauthorised use and change.","Because the override was reversed, Internal Audit need not report A3 to the Audit Committee."]}'::jsonb, '{"values": [0,1,3]}'::jsonb, 'Pressure and opportunity interact; fixing only one leaves residual risk. A5 is a pure incentive/pressure finding. ITGCs constrain opportunity. A1 is opportunity, not rationalisation. Reversal does not absolve reporting a significant access-control failure.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);

-- Case 2: Kollam Cashew Processors — FIFO process costing
with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 1', 'Cost Management', 'Kollam Cashew Processors — FIFO process costing', 'Kollam Cashew Processors runs a single roasting department that converts shelled cashews into packaged kernels. The department uses a <b>FIFO</b> process-costing system. Materials are added at the start of the process; conversion costs are incurred evenly.

Production and cost data for May are set out in Exhibits 1 and 2. There is no spoilage. The Cost Accountant has asked you to compute equivalent units, cost per equivalent unit, and the cost of production report figures the Board pack requires.', '[{"label": "Exhibit 1 — Physical flow (units)","caption": "Roasting department, May","columns": ["Description","Units"],"rows": [["Opening WIP (100% materials, 40% conversion)","5,000"],["Started during May","25,000"],["Completed and transferred out","22,000"],["Ending WIP (100% materials, 25% conversion)","8,000"]]},{"label": "Exhibit 2 — Costs","caption": "Roasting department, May","columns": ["Cost element","Opening WIP","Added in May"],"rows": [["Materials","$40,000","$200,000"],["Conversion","$16,000","$154,000"],["Total","$56,000","$354,000"]]}]'::jsonb, 'Hard', 'fets_v2', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'num', 12, 'Under FIFO, calculate <b>equivalent units for materials</b> for May.', 'Whole units. Materials are added at the start of the process.', '{}'::jsonb, '{"value": 25000}'::jsonb, 'Opening WIP already 100% complete for materials, so 0 EU to finish it. Started and completed = 22,000 - 5,000 = 17,000. Ending WIP = 8,000 x 100% = 8,000. EU materials = 0 + 17,000 + 8,000 = 25,000.'),
  (2, 'num', 12, 'Under FIFO, calculate <b>equivalent units for conversion</b> for May.', 'Whole units.', '{}'::jsonb, '{"value": 22000}'::jsonb, 'To complete opening: 5,000 x (1 - 0.40) = 3,000. Started and completed = 17,000. Ending WIP = 8,000 x 25% = 2,000. EU conversion = 3,000 + 17,000 + 2,000 = 22,000.'),
  (3, 'list', 16, 'Complete the statement of cost per equivalent unit (FIFO).', NULL, '{"fields": [{"label": "Materials cost per equivalent unit is","options": ["$8.00","$9.60","$7.00","$8.16"]},{"label": "and conversion cost per equivalent unit is","options": ["$7.00","$8.00","$7.72","$6.16"]}]}'::jsonb, '{"values": ["$8.00","$7.00"]}'::jsonb, 'Materials: $200,000 / 25,000 = $8.00. Conversion: $154,000 / 22,000 = $7.00. FIFO uses only costs added this period in the rate calculation.'),
  (4, 'num', 16, 'Calculate the <b>total cost of units completed and transferred out</b> in May under FIFO.', 'Whole dollars, no commas.', '{}'::jsonb, '{"value": 332000}'::jsonb, 'Opening WIP costs $56,000 + conversion to finish opening 3,000 x $7 = $21,000 + started-and-completed 17,000 x ($8 + $7) = $255,000 = $332,000.'),
  (5, 'num', 14, 'Calculate the <b>cost of ending work in process</b> at 31 May.', 'Whole dollars, no commas.', '{}'::jsonb, '{"value": 78000}'::jsonb, 'Materials 8,000 x $8 = $64,000 + conversion 2,000 x $7 = $14,000 = $78,000. Check: $56,000 + $354,000 = $410,000; $332,000 + $78,000 = $410,000.'),
  (6, 'dnd', 16, 'Classify each statement as true of <b>FIFO</b> process costing, <b>weighted-average</b> process costing, or <b>both</b>.', NULL, '{"items": [{"id": "a","text": "Separates work done in the prior period from work done this period"},{"id": "b","text": "Blends opening WIP costs into the current-period unit cost"},{"id": "c","text": "Requires a physical-flow reconciliation of units"},{"id": "d","text": "Computes equivalent units only for work performed this period"}],"zones": {"fifo": "FIFO only","wa": "Weighted-average only","both": "Both methods"}}'::jsonb, '{"placement": {"a": "fifo","b": "wa","c": "both","d": "fifo"}}'::jsonb, 'FIFO isolates prior-period work and costs; weighted average merges opening costs into the unit rate. Both methods begin with a physical-flow (units) reconciliation.'),
  (7, 'mcq', 14, 'If the department had instead used weighted-average costing, which figure would change?', NULL, '{"options": ["Equivalent units for materials and conversion, and therefore cost per EU and the cost assignment","Physical units completed and transferred out","Total costs to account for ($410,000)","The fact that materials are added at the start of the process"]}'::jsonb, '{"value": "A"}'::jsonb, 'Weighted average redefines EU (opening + started work counted together) and folds opening costs into the rate, changing cost per EU and the assignment. Physical completions and total costs to account for are method-independent; material timing is a process fact.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);

-- Case 3: Kozhikode Spices Limited — inventory valuation and revenue cut-off
with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 1', 'External Financial Reporting', 'Kozhikode Spices Limited — inventory valuation and revenue cut-off', 'Kozhikode Spices Limited exports ground spice blends and holds both owned inventory and goods placed with distributors on consignment. The year-end is 31 March. The Financial Controller is finalising inventory valuation and revenue cut-off and has given you the schedules in Exhibits 1 and 2.

Inventory is measured at the lower of cost and net realisable value under Ind AS 2 / IAS 2. Revenue is recognised under Ind AS 115 / IFRS 15 when control transfers. Management has proposed recognising a bill-and-hold arrangement described in Exhibit 2 and is seeking confirmation that the criteria are met.', '[{"label": "Exhibit 1 — Inventory positions at 31 March","caption": "Before year-end adjustments","columns": ["Line","Description","Cost","Estimated NRV","Notes"],"rows": [["1","Cardamom blend — finished goods (owned warehouse)","$120,000","$95,000","Oversupply; slow moving"],["2","Pepper grind — finished goods on consignment at retail distributor","$80,000","$110,000","Distributor has not sold to end customers"],["3","Turmeric powder — finished goods","$60,000","$72,000","Normal demand"],["4","Raw black pepper — raw materials","$45,000","$40,000","Market price decline"]]},{"label": "Exhibit 2 — Revenue and cut-off items","caption": "Transactions under review","columns": ["Item","Detail"],"rows": [["Bill-and-hold Order BH-17","Invoice $150,000 dated 28 March; customer requested delay of shipment until 12 April for warehouse space; goods segregated, ready, and cannot be redirected; customer accepted billing and risk"],["Shipment S-904","Goods costing $28,000, invoiced $40,000, loaded on carrier 31 March under FOB shipping point terms; arrived at customer 2 April"],["Shipment S-911","Goods costing $18,000, invoiced $26,000, still in Kozhikode warehouse at close of 31 March; FOB destination; delivered 3 April"],["Consignment sales report","Distributor sold $35,000 (cost $22,000) of consigned pepper grind to end customers in March; remittance due April"]]}]'::jsonb, 'Hard', 'fets_v2', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'num', 12, 'Calculate the <b>total write-down to NRV</b> required for inventory lines 1 and 4 combined.', 'Whole dollars. Write down only where NRV is below cost.', '{}