-- CBQ cases v2 (source=fets_v2). INSERT only — does NOT delete existing cases.
-- Generated for CoStudy CMA-style CBQ. 6 cases x 7 tasks.

-- Case 1: Palakkad FinTech Services — IT general controls and fraud risk
with c as (
  insert into public.cbq_cases (part, section, title, narrative, exhibits, difficulty, source, verified)
  values ('Part 1', 'Internal Controls', 'Palakkad FinTech Services — IT general controls and fraud risk', 'Palakkad FinTech Services operates a regional digital-payments platform that settles merchant collections for more than 4,000 Kerala retailers. Settlements are posted overnight by an automated batch job; exceptions are cleared the next morning by the Operations team.

During a routine review the Internal Audit Manager identified several control weaknesses (Exhibit 1) and has asked you to evaluate them against the fraud triangle and against IT general-control expectations. Separately, a junior settlement clerk was found to have overridden an exception that delayed a Rs 2,400,000 remittance; the override was later reversed, but the incident has raised Board concern.

The company applies a COSO-based control framework. Management estimates that an undetected fraudulent settlement diversion lasting one month would expose roughly Rs 18,000,000 of platform float (Exhibit 2).', '[{"label": "Exhibit 1 — Control observations","caption": "Internal audit findings, quarter ended 30 June","columns": ["Ref","Observation"],"rows": [["A1","Three Operations staff share a single privileged OS login for the settlement server"],["A2","Change tickets to the batch settlement code are approved by the same developer who writes them"],["A3","Exception overrides require a second password, but the password is posted on a shared whiteboard"],["A4","Monthly access reviews of the settlement application have not been performed for eight months"],["A5","Night-shift supervisors are paid a bonus tied solely to clearing all exceptions before 09:00"]]},{"label": "Exhibit 2 — Float and incident data","caption": "Management estimates","columns": ["Item","Amount / detail"],"rows": [["Average month-end platform float at risk","Rs 18,000,000"],["Estimated probability of a successful diversion if A1-A3 remain unremediated","8%"],["Expected detection lag if A4 remains unremediated","45 days"],["Override incident amount (later reversed)","Rs 2,400,000"],["Annual cost of proposed privileged-access management tool","Rs 720,000"]]}]'::jsonb, 'Hard', 'fets_v2', true)
  returning id)
insert into public.cbq_tasks (case_id, seq, type, marks, prompt, hint, payload, answer, explanation)
select c.id, t.seq, t.type, t.marks, t.prompt, t.hint, t.payload, t.answer, t.explanation from c, (values
  (1, 'dnd', 16, 'Place each observation against the element of the <b>fraud triangle</b> it most directly increases. <b>All five must be placed.</b>', NULL, '{"items": [{"id": "a","text": "A1 — shared privileged OS login"},{"id": "b","text": "A2 — developer self-approves change tickets"},{"id": "c","text": "A3 — override password on a whiteboard"},{"id": "d","text": "A4 — access reviews not performed for eight months"},{"id": "e","text": "A5 — bonus tied solely to clearing exceptions by 09:00"}],"zones": {"opp": "Opportunity","press": "Pressure / incentive","rat": "Rationalisation"}}'::jsonb, '{"placement": {"a": "opp","b": "opp","c": "opp","d": "opp","e": "press"}}'::jsonb, 'Shared credentials, self-approved changes, a public override password and unreviewed access all expand the chance to commit and conceal fraud — opportunity. The 09:00 bonus creates a performance incentive that can pressure staff to clear exceptions improperly. None of the findings primarily describes rationalisation.'),
  (2, 'multi', 14, 'Which of the following are <b>IT general controls</b> rather than application controls? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply","options": ["Privileged operating-system access management on the settlement server","Program-change approval and segregation for the batch settlement code","A field edit that rejects a settlement amount exceeding the merchant''s daily limit","Periodic user-access reviews for the settlement application","An automated three-way match of invoice, receipt and purchase order inside the AP module"]}'::jsonb, '{"values": [0,1,3]}'::jsonb, 'OS access, change management and access reviews are ITGCs that support the reliability of the processing environment. Field edits and three-way matching are application controls embedded in specific business processes.'),
  (3, 'num', 14, 'Calculate the <b>expected annual loss</b> from an undetected diversion if observations A1-A3 remain unremediated, using the float and probability in Exhibit 2. Ignore the detection lag for this task.', 'Whole rupees, no commas or currency symbol.', '{}'::jsonb, '{"value": 1440000}'::jsonb, 'Rs 18,000,000 x 8% = Rs 1,440,000 expected annual loss.'),
  (4, 'list', 14, 'Complete the following statement about the override incident.', NULL, '{"fields": [{"label": "The shared whiteboard password primarily represents a failure of","options": ["segregation of duties","physical and logical access control","input validation","backup and recovery"]},{"label": "and the fact that the override was later reversed means the residual financial misstatement was","options": ["Rs 2,400,000","nil for the reported period once reversed","Rs 18,000,000","Rs 720,000"]}]}'::jsonb, '{"values": ["physical and logical access control","nil for the reported period once reversed"]}'::jsonb, 'Posting a second-factor password publicly defeats logical access control. Because the override was reversed, the financial statements for the period do not retain a Rs 2,400,000 misstatement — though the control failure itself remains a significant deficiency.'),
  (5, 'mcq', 14, 'Relative to the expected annual loss calculated earlier, is the proposed privileged-access management tool cost-justified on a pure expected-loss basis?', NULL, '{"options": ["Yes — annual tool cost of Rs 720,000 is below the Rs 1,440,000 expected loss.","No — the tool costs more than the expected loss.","Indifferent — tool cost equals expected loss.","Cannot tell — detection lag must be known first."]}'::jsonb, '{"value": "A"}'::jsonb, 'Rs 720,000 < Rs 1,440,000, so on a pure expected-loss comparison the tool is cost-justified. (A fuller business case would also weigh residual risk and qualitative regulatory exposure.)'),
  (6, 'dnd', 14, 'Classify each proposed remediation as primarily <b>preventive</b> or <b>detective</b>.', NULL, '{"items": [{"id": "a","text": "Issue unique privileged credentials and enforce MFA on the settlement server"},{"id": "b","text": "Require independent CAB approval before production changes go live"},{"id": "c","text": "Resume monthly user-access reviews with exception reporting to Internal Audit"},{"id": "d","text": "Reintroduce an overnight exception log reviewed the next morning by a non-ops supervisor"}],"zones": {"prev": "Preventive","det": "Detective"}}'::jsonb, '{"placement": {"a": "prev","b": "prev","c": "det","d": "det"}}'::jsonb, 'Unique credentials, MFA and independent change approval stop unauthorised acts before they occur. Access reviews and exception-log reviews discover problems after the fact.'),
  (7, 'multi', 14, 'Which statements about the fraud triangle and this case are correct? <b>Select all that apply.</b>', NULL, '{"selectCount": "all that apply","options": ["Removing opportunity alone can still leave residual fraud risk if pressure remains high.","A5 increases pressure even though it does not itself create an access path.","Rationalisation is evidenced directly by the shared OS login in A1.","IT general controls primarily address opportunity by limiting unauthorised use and change.","Because the override was reversed, Internal Audit need not report A3 to the Audit Committee."]}'::jsonb, '{"values": [0,1,3]}'::jsonb, 'Pressure and opportunity interact; fixing only one leaves residual risk. A5 is a pure incentive/pressure finding. ITGCs constrain opportunity. A1 is opportunity, not rationalisation. Reversal does not absolve reporting a significant access-control failure.')
) as t(seq, type, marks, prompt, hint, payload, answer, explanation);

-- Case 2: Kollam Cashew Processors — FIFO process costing
